.TH automan 1W "1997.11.14" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
automan - 自動検測処理の割り当て
.SH 形式
automan
.LP
.SH 解説
automan は常時実行されており、events(1W) から処理を依頼されたイベント波形の
処理を空いているホストに割り当てます。events(1W) からの処理の依頼は、
/dat/auto に波形ファイルと同名の、大きさゼロのファイルが作られる
（touchされる）ことによって行われます。ファイル /dat/autos/ORDER は自動検測処理に
参加するホスト名が１行に１つずつ書かれたリストで、先頭が "#" の行は
読み飛ばされます。これらのホストに対応して、
/dat/autos にはこれらのホスト名をもつディレクトリがあります。pmon は数十秒ごとに
/dat/auto を検査し、そこに touch されたファイルがある場合は、その中からもっとも
早い時間のファイルをいずれかのホストに割り当てようとします。pmon は
/dat/autos/ORDER を先頭から見ていき、そのうち最初に見つけた自動検測処理中
でないホストに処理を依頼します。自動検測処理中であるかどうかは
ディレクトリ /dat/autos/ホスト名 にファイルがあるかどうかで判断され、
処理の依頼はその同じディレクトリに /dat/auto からファイルをもってくる（mvする）
ことによって行われます。あとの自動検測処理は autopick(1W) が win(1W) を
自動処理モードで起動することによって行われるのが普通です。
.LP
automan は通常 _win(1W) からバックグラウンドで起動されます。
.SH オプション
.TP 
なし
.SH ソース
.TP
`automan'
.SH 関連事項
_win(1W), events(1W), autopick(1W), win(1W)

