.TH chtbl_ck 1W "2011.8.3" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
chtbl_ck - チャネルテーブルファイルの内容の検査
.SH 形式
chtbl_ck 
.I file
.LP
.SH 解説
chtbl_ck は チャネルテーブルファイル
.I file
の内容を検査し、結果を標準出力に書き出します。チャネルテーブルのフォー
マットについては win(1W) を参照して下さい。検査の内容は、
.IP \(bu ・)
チャネル番号が重複していないか。
.IP \(bu ・)
観測点コードと座標及び観測点補正情報は1対1の関係であるか。
.IP \(bu ・)
空白行が無いか
.IP \(bu ・)
フィールド数が13か16以上か。
.LP
です。
.SH 関連事項
win(1W)
