.TH ck_ls8800cst 1W "2011.9.16" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
ck_ls8800cst - LS8800 の時刻較正ログからGPS時計とデータの時刻差の表示
.SH 形式
ck_ls8800cst [\-\fBt\fI threshold\fR]
.LP
.SH 解説
ck_ls8800cst は標準入力からLS8800の時刻較正ログを読み込み、
結果を標準出力に書き出します。出力内容は、時刻較正をした時刻、時刻較正
が成功したかどうか？、GPS時計とデータの時刻差(マイクロ秒単位)です。も
し時刻差が 5 ミリ秒以上ある場合は、* も追加されます。この閾値は
.I t
オプションで変更可能です。

.SH オプション
.IP "\fB\-t\fI threshold\fR" 5
* を出力する閾値を、
.I threshold
マイクロ秒にします。整数値で与えなくてはいけません。デフォルトは、5 ミ
リ秒です。
