.TH cormeisei 1W "2000.12.21" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
cormeisei - GTA-45Uデータのリアルタイム最小位相特性化
.SH 形式
cormeisei
.I inkey
.I outkey
.I shmsize
.I chfile
[
.I logfile
]
.LP
.SH 解説
cormeisei は、キー
.I \ inkey
の共有メモリ・セグメントに巡回的に書き込まれている、
時間順に整列された win 形式のデータを読み込み、
チャネル設定ファイル
.I chfile
に指定されたチャネルのデータについては、明星電気製
GTA-45UでAD変換された直線位相特性であると仮定して
最小位相特性に変換し、その他のチャネルについては
そのまま、いずれも
キー
.I \ outkey
で与えられる共有メモリ・セグメントに書き出します。
キー
.I \ outkey
をもつ共有メモリ・セグメントが存在しない場合は、大きさ
.I \ shmsize
\ (KB) の共有メモリ・セグメントが作られます。すでに存在している場合は、
そのサイズが
.I \ shmsize
\ (KB) よりも小さいとエラーになります。
共有メモリ・キーは32ビットの整数値です。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられ、
指定しないとログ情報は標準出力に
送られます。ログファイルは書き込みのたび毎に
オープン／クローズされます。
.LP
チャネル設定ファイルは、１行に１チャネル分ずつ、16進数のチャネル番号と
そのチャネルのサンプリングレートを、空白またはタブで区切って書
き並べたテキストファイルです。各行の先頭から２項目だけが読まれ、
空白またはタブで区切られた以降の項目は無視されます。また先頭
が '#' である行も無視されます。サンプリングレートは 20 (Hz) または
100 (Hz) で、実際のデータのそれと一致していなければなりません。
cormeisei プロセスは
ハングアップシグナルを受け取ると、チャネル設定ファイルを読み直します。
共有メモリ
.I inkey
および
.I outkey
上のデータ形式は、時間順整列されたもの(order(1W)参照)
でなければなりません。
.LP
cormeisei の出力は、内部の処理のために入力よりも12秒程度遅れて
出てきます。
.LP
cormeisei は、引数なしで起動すると簡単な使用法を表示します。
.LP
.SH オプション
.TP 
なし
.SH ソース
.TP
`cormeisei.c'
.SH 関連事項
winformat(1W), order(1W)
.SH 作者
井出 哲。
.SH 参考文献
井出 哲・卜部 卓, 全域通過フィルタによる非因果的地震波記録の
リアルタイム位相補正, 東大地震研技術報告, No.3, 20-28, 1998.
