.TH dewin 1W "1997.12.5" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
dewin - win 形式ファイルから単一チャネルのデータの抜き出し
.SH 形式
dewin [ \-acnh ]
.I channel
[
.I file
]
.LP
.SH 解説
dewin は、win 形式ファイル
.I \ file
から、16進数のチャネル番号
.I \ channel
のデータを抜き出して、内部表現の４バイト整数で標準出力へ
書き出します。
.I \ file
が与えられない場合は、データを標準入力から読みます。
.LP
dewin は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP
\-a
出力形式をμ-lawのオーディオデータ形式で書き出します。
.TP
\-c
出力形式をテキスト形式にします。１行１データで
整数値が書き出されます。
.TP
\-n
入力データが時間的に不連続（つまり１つまたは複数の秒が抜けている）
であったとき、抜けた部分は無視します。これを指定しないと、抜けた
部分には値ゼロのデータが詰められます。
.TP
\-h
簡単な使用法を表示します。
.SH ソース
.TP
`dewin.c'
.SH 関連事項
win(1W), wed(1W), wck(1W), wadd(1W), winformat(1W)
