.TH dewin 1W "2001.1.15" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
dewin - win 形式ファイルから単一チャネルのデータの抜き出し
.SH 形式
dewin [\-\fBacnh\fR] [\-\fBf\fI filter\fR]
.I channel
[
.I file
]
.LP
.SH 解説
dewin は、win 形式ファイル
.I \ file
から、16進数のチャネル番号
.I \ channel
のデータを抜き出して、内部表現の４バイト整数で標準出力へ
書き出します。
.I \ file
が与えられない場合は、データを標準入力から読みます。
.LP
dewin は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.IP "\fB\-a" 5
出力形式をμ-lawのオーディオデータ形式で書き出します。
.IP "\fB\-c" 5
出力形式をテキスト形式にします。１行１データで
整数値が書き出されます。
.IP "\fB\-f\fI filter\fR" 5
出力データにフィルタをかけます。フィルタの特性は
ファイル
.I filter
で与えます。
このファイルの書式は win(1W) のフィルタ設定ファイルと同じで、
フィルタは1行の中で空白で区切った5〜6個の項目で設定します。
"#"で始まる行は無視されます。次に例を示します。
ここでは2行目に設定してあるパラメタが使用されます。
他の行はコメントとして無視されます。
.IP
.nf
   #bpf fl=5.0 fh=20.0 fs=30.0 ap=0.5 as=5.0
   hpf fp=1.0 fs=0.5          ap=0.5 as=5.0
   #lpf fp=0.5 fs=0.8          ap=0.5 as=5.0
   #bpf fl=8.0 fh=16.0 fs=24.0 ap=0.5 as=5.0
.fi
.IP
フィ ルタはバターワース特性のローパス、ハイパス、バンドパスの３種類です。
係数の決定とフィルタリン グには、
.RS
.IP
斉藤正徳,1978,漸化式ディジタル・フィルターの自動設計,物理探鉱,31, 112-135
.RE
.IP
のプログラムを使用しています。設定パラメタの選び方についてはこの
文献を参照してください。
.IP "\fB\-n" 5
入力データが時間的に不連続（つまり１つまたは複数の秒が抜けている）
であったとき、抜けた部分は無視します。これを指定しないと、抜けた
部分には値ゼロのデータが詰められます。
.IP "\fB\-j" 5
1行1データのテキスト形式でタイムスタンプと共にデータを書き出します。
-c オプションが自動的に設定されます。
.IP "\fB\-e" 5
1行1データのテキスト形式で経過時間（単位は秒）と共にデータを書き出します。
-c オプションが自動的に設定されます。
.IP "\fB\-h" 5
簡単な使用法を表示します。
.SH ソース
.TP
`dewin.c'
.SH 関連事項
win(1W), wed(1W), wck(1W), wadd(1W), winformat(1W)
