.TH ecore 1W "1995.7.25" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
ecore - win 形式ファイルから JARRAY データを作る
.SH 形式
ecore
.I start
.I end
.I rawdir
.I chfile
[
.I outdir
]
.LP
.SH 解説
ecore は、
.I \ rawdir
ディレクトリにある１分毎の連続 win 形式ファイルから、
時刻
.I start
から
.I end
までの期間について、チャネル表ファイル
.I \ chfile
に指定されたチャネルのデータを抜き出してローパスフィルターを
かけ、サンプリングレート 20Hz に間引いた２バイト整数の固定長
ファイルとして
.I \ outdir
に出力します。
.I outdir
を省略すると、カレントディレクトリに出力されます。
出力ファイルは指定された期間分が１つのファイルになり、内容は
１サンプル間隔ごとにチャネル数だけのデータが並ぶ形式
（チャネル・マルチプレクスされた形式）です。
出力ファイル名は、
.I start
と同じになります。
.LP
.I start
と
.I \ end
は、年月日時分それぞれ２桁で、'YYMMDDhh.mm' の形式です。
.I end
に指定された「分」の終わりまでが出力されます。
.I chfile
は、１行に１つずつ、16進数でチャネル番号を書いたもので、
各行の先頭の１項目だけが読まれ、残りは無視されます。
先頭が '#' の行は無視されます。
.LP
入るべきチャネルのデータがない場合には、データ '0' が入ります。
値が２バイト整数からオーバーフローする場合、データは -32768 また
は 32767 にクリップされます。
.LP
.I rawdir
では、書き込まれた最新の win 形式ファイル名（'YYMMDDhh.mm' 形式）
が、ファイル LATEST の内容として書かれていなければなりません。
通常、
.I rawdir
は wdisk(1W) または fromtape(1W) の出力ディレクトリです。
ecore は、処理を終わった win 形式ファイル名を、
.I rawdir
のファイル USED に書き込みます。
.LP
ecore は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース
.TP
`ecore.c'
.SH 関連事項
fromtape(1W), wdisk(1W)
