.TH elist 1W "1997.12.10" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
elist - トリガー・検測情報データベースを作る
.SH 形式
elist
.I pickdir
.I pmonout
[ \fItrgdir\fR [ \fIdir1\fR [ \fIdir2\fR [ \fIdir3\fR ]]]]
.LP
.SH 解説
elist は、pmon(1W) が生成したトリガーリストファイル
.I pmonout
からトリガー情報を読み込み、新しいものから順に１行１イベントの形式で、
(1)トリガー時刻、(2)検測状況、(3)マグニチュードの目安、
(4)トリガーした地域名のリスト、を標準出力に書き出します。
(1)のトリガー時刻は
.I pmonout
中の「on時刻」で、これは events(1W) が生成した
イベント波形ファイル名でも
あります。す。(2)の検測状況には、検測情報ファイルの
ディレクトリ
.I pickdir
からそのイベント波形ファイルに属する検測情報ファイルを探し、その
内容から(A)検測者名、(B)ラベル（メモ）、(C)検測レベルが書き出されます。
(A)と(B)は最初の５文字までが表示されます。(C)は"PHMM"の４文字で
表示され、それぞれの文字は読み取り値があること(P)、震源決定されて
いること(H)、マグニチュードが決定されていること(M)、メカニズムが決定
されていること(M)、を表します。それらの文字のかわりに"."があると、
対応する情報がない、または決定されてないことを示します。１つの
そのイベント波形ファイルに属する検測情報ファイルが複数あるときは、
その数だけ(2)すなわち(A)〜(C)が書き並べられます。
(3)のマグニチュードの目安はトリガー継続時間から経験式で求められ、
マグニチュードが星の数で表されます。(4)のトリガーした地域名のリストは、
.I pmonout
の on行と off行から得られるもので、トリガーした時間順に書き並べられます。
.LP
.I trgdir
を指定すると、もしそのディレクトリにそのトリガーに対応する
イベント波形ファイルがない場合、(1)のトリガー時刻（＝イベント波形ファイル名）の
後ろに "x" が付けられます。また、(2)の(B)のラベルが "NOISE" であるとき、
elist は
.I trgdir
にある、対応するイベント波形ファイルおよびそれに付属するチャネル表ファイル
（〜.ch）とビットマップファイル（〜.sv）を削除します。
通常
.I trgdir
として指定されるのは /dat/trg です。
.LP
ディレクトリ
.I dir1 ...
が指定されているとき、このディレクトリのいずれかの中
（ただしディレクトリ名が "/" で終わっている場合はその下のすべての
ディレクトリの中）にイベント
波形ファイルと同じ名前をもつファイルがあると、(1)のトリガー時刻
（＝イベント波形ファイル名）の後ろに "&" が付けられます。
通常
.I dir1 ...
として指定されるのは /dat/auto, /dat/autos/, /dat/request/ 等です。
.LP
elist はイベント収録サーバーで _update(1W) の中で使われています。
.LP
elist は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース
.TP
`elist.c'
.SH 関連事項
_update(1W), pmon(1W)
