.TH extraw 1W "2000.12.20" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
extraw - データパケットと制御パケットを分離する
.SH 形式
extraw
.I inkey
.I datkey
.I datsize
.I ctlkey
.I ctlsize
[
.I logfile
]
.LP
.SH 解説
extraw は、キー
.I \ inkey
の共有メモリ・セグメントに巡回的に書き込まれている
「パケット種別付き」の win 形式のデータを読み込み、
パケット種別にしたがってパケットをデータ（種別コード
"A1"〜"A4"）と制御パケット（種別コード"A1"〜"A4"以外）に分け，
パケット種別コードを取り去って、
それぞれを、キー
.I \ datkey
およびキー
.I \ ctlkey
で与えられる２つの共有メモリ・セグメントに書き出します。
キー
.I \ datkey
および
.I \ ctlkey
をもつ共有メモリ・セグメントが存在しない場合は、それぞれ
大きさ
.I \ datsize
\ (KB) 
および
.I \ ctlsize
\ (KB)
の共有メモリ・セグメントが作られます。それらがすでに
存在している場合は、その大きさがそれぞれ指定された
大きさよりも小さいとエラーになります。
共有メモリ・キーは32ビットの整数値です。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられ、
指定しないとログ情報は標準出力に
送られます。ログファイルは書き込みのたび毎に
オープン／クローズされます。
.LP
入力側共有メモリ
.I inkey
上の形式としては、"A1"以上の種別コードが付いたパケットの
データを想定しており，これは recvs(1W) や \-a オプション
付きの recvt(1W) 等のプロセスで受信/書き込みされるものです。
データ形式の詳細はこれらの項を参照してください。
.LP
出力側共有メモリ
.I datkey
/
.I ctlkey
のデータ形式は，種別コードのない、通常の書き込み時刻付き形式です。
データ形式の詳細は recvt(1W) を参照してください。
.LP
extraw は、引数なしで起動すると簡単な使用法を表示します。
.LP
.SH オプション
.TP 
なし
.SH ソース
.TP
`extraw.c'
.SH 関連事項
winformat(1W), recvt(1W), recvs(1W)
