'\" t
.TH hypomh 1W "1998.2.18" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
hypomh - 平田・松浦による震源決定プログラム
.SH 形式
hypomh
.I stan
.I seis
.I final
.I report
[
.I init
]
.SH 解説
ここでは win(1W)が呼び出している hypomh を、winの外で単独で使う
方法を解説します。他に、pickfile(1W)、win(1W)も参考になります。
引き数は次のとおりです。
.TP
.I stan
速度構造ファイル。win で使っているのと同じものでよい。フォーマットは
win(1W)参照。
.TP
.I seis
到着時刻と観測点座標のデータファイル。
win の験測情報ファイル（pickファイル）中では、
"#s"で始まる部分から"#s"を取り除いたもの。フィルタ seis(1W) で
作れる。フォーマットは pickfile(1W)参照。例えば、
.br
 cat /dat/picks/man/9307/930715.152345.123 | seis > tmp
.br
複数の地震のデータを入れておけば、つぎつぎに処理される。たとえば、
.br
 cat /dat/picks/man/9307/930715* | seis > tmp
.TP
.I final
結果を出力するファイル。win の pickファイル中では、
"#f"で始まる部分から"#f"を取り除いたもの。
フォーマットは pickfile(1W)参照。
.TP
.I report
計算中の経過を出力するファイル。いらないときは /dev/null を指定する。
.TP
.I init
初期値のファイル。初期震源の緯度(度)、経度(度)、
深さ(km)を１行目に、それぞれの不確定さ(km)を２行目に書く。
値はいずれも小数点付きで、各項目の幅は12桁ずつ。
このファイルを指定しないと、構造ファイルに指定した値が使われる。
.LP
計算結果を地図に表示するには、結果ファイル(\fI final\fR )の
１行目
(" 93  7 22    12  6   2.162   34.76181  140.09901  60.004   2.0"など)
のみを切りだしたファイルを作って、このファイル名を win.prm の
14行目に書き、win -m で見るのが一番簡単です。
.SH ソース
.TP
`hypomh.f'
.SH 関連事項
win(1W), pickfile(1W), seis(1W)
