.TH ls7000_A8 1W "2009.3.6" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
ls7000_A8 - 白山 LS8TEL ファームの設定情報(A8)データの表示
.SH 形式
ls7000_A8 file ...
.LP
.SH 解説
ls7000_A8 は、白山工業社製データロガーLS-7000(無印)の設定情報(A8パケッ
トのデータ本体部分)を読み込み、情報の一部を標準出力に表示します。
.LP
表示する内容は、時刻、ロガーアドレス、ファームウェアの名前(日付)、通信
速度、サンプリング周波数、全6チャンネルのゲイン設定(倍率、ビット数)です。
.SH オプション
なし
.SH ソース
.TP
`ls7000_A8.c'
.SH 関連事項
recvstatus4(1W), ls7000_A9(1W)
