.TH ls7000_A9 1W "2009.3.6" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
ls7000_A9 - 白山 LS7000無印の動作情報(A9)データの表示
.SH 形式
ls7000_A9 file ....
.LP
.SH 解説
ls7000_A9 は、白山工業社製データロガーLS-7000(無印)の動作情報(A9パケッ
トのデータ本体部分)を読み込み、情報の一部を標準出力に表示します。
.LP
表示する内容は、時刻、ロガーアドレス、アルマナック日付、使用衛星(全8チャ
ンネル。00 は使用していないことを示す)、誤差情報(ミリ秒単位)です。使用
衛星が8個ともすべて 00 の場合、時刻較正に失敗したことを示しており、*
が付きます。また、誤差情報の末尾に、5msec (200Hz の時のサンプル間隔)
以上の誤差がある場合は * が、10msec (100Hz の時のサンプル間隔)以上の誤
差がある場合は ** が付記されます。 
.SH オプション
なし
.SH ソース
.TP
`ls7000_A9.c'
.SH 関連事項
recvstatus4(1W), ls7000_A8(1W)
