.TH newym 1W "2001.2.7" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
newym - イベント収録サーバーでの月切り替え処理
.SH 形式
newym [\fIdat_dir\fR] 
.LP
.SH 解説
newym はイベント収録サーバーにおいて、月別の構成になっている
トリガーリストや、検測情報ファイル(pickファイル)ディレクトリの
月替わり処理を行います。newym は通常 _bj(1W)や_bj2(1W)から
定期的(たとえば数10秒ごと)に起動されますが、実際に働くのは
月替わり処理がまだ終ってない新しい月の２日以降に起動された
ときだけです。newym は環境変数 DD または引数
.I dat_dir
で与えられたディレクトリの下について、作業を行います。DD と
.I dat_dir
の両方が与えられた場合は
.I dat_dir
が優先されます。newym が行う処理は以下のものです。以下では
ディレクトリ /dat が指定され、年月が 0101 から 0102 へ切り替わる
場合について解説します。
.IP "" 3
.ti -3
(1)収録システムとしての現在の「年月」を保持するファイル
/dat/etc/YYMM の内容を "0101" から "0102" に書き換える。
.IP "" 3
.ti -3
(2) pmon(1W) と events(1W) に STOPシグナルを送って一旦停止させ、
その間に /dat/etc/pmon.out.0101 ファイル中の新しい月の部分を
新しく生成したファイル /dat/etc/pmon.out.0102 に移し、/dat/etc/pmon.out
のシンボリックリンク先を /dat/etc/pmon.out.0101 から
/dat/etc/pmon.out.0102 へ変更しする。最後に pmon(1W) と events(1W) に
CONT シグナルを送って実行再開させる。
.IP "" 3
.ti -3
(3)pickファイルのディレクトリ /dat/picks/man/0101 中の、0102分の
pickファイルを新しく生成したディレクトリ /dat/picks/man/0102 に
移動させる。
.IP "" 3
.ti -3
(4)pickファイルのディレクトリ /dat/picks/auto/0101 中の、0102分の
pickファイルを新しく生成したディレクトリ /dat/picks/auto/0102 に
移動させる。
.LP
なお、(2)でnewymは _stop(1W) と _cont(1W) を使用しますが、
その際には対象としているイベント処理系の pmon/events だけでなくて、
そのマシンで実行しているすべての pmon/events プロセスに
シグナルが送られます。また、(3)と(4)はそれぞれディレクトリ
/dat/picks/man または /dat/picks/man が存在してなければ行われません。
.SH オプション
.TP 
なし。
.SH ソース
.TP
`newym'
.SH 関連事項
_stop(1W), _cont(1W), events(1W), pmon(1W), _bj(1W), _bj2(1W)
