.TH order2 1W "2002.5.31" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
order2 - 共有メモリ中の win 形式データの時間順整列
.SH 形式
order [\-\fBaB\fR] [\-\fBl\fI key:size\fR]
.I inkey
.I outkey
.I shmsize
.I limit
.I outkey2
.I shmsize2
[
.I logfile
]
.LP
.SH 解説
order2 は order(1W) とほぼ同じ機能を持ちます。order(1W) と異なるのは、
.I limit 
秒より遅れてきたデータを、
.I shmsize2
KBの大きさの、キー
.I outkey2
の共有メモリに書き出す点です。
.I outkey2
に書き出すデータのフォーマットは、「書き込み時刻」付き、つまり、
recvt(1W) が書き込む時と同じフォーマットです。 
.LP
.SH 注
現在の order(1W) はオプション
.I \-l
を指定することにより order2 の動作をすることができます。
.SH ソース
.TP 
`order2.c'
.SH 関連事項
wdiskts(1W), recvt(1W), order(1W)
