'\" t
.TH pickfile 1W "2001.6.7" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
pickfile - win の検測情報ファイル
.SH 解説
ここでは win の検測情報ファイル（pickファイル）の内容について
解説します。
.LP
winの験測情報は /dat/picks/man/9802 等の月別のディレクトリに、
１地震１ファイルの形で入っています。これを pickファイルと呼んでいます。
そのファイル名は、ふつうもっとも早いP時刻を使って、YYMMDD.hhmmss.sssの
形で作られます（win(1W)）。
.LP
pickファイルは、
.IP
.ti -3n
(1)"#p"で始まる行、これはwinが読み書きする生の験測情報。
.br
.ti -3n
(2)"#s"で始まる行、震源決定プログラムhypomhへの入力形式で、走時データと
観測点情報を含む。
.br
.ti -3n
(3)"#f"で始まる行、hypomhの出力形式で、震源決定結果。
.LP
の３つの部分からなります。(1)〜(3)を直接書きだすのはwinですが、(2)の
部分はwinが震源決定をするたびにwinが(1)から生成してhypomhに与える
もののコピー、(3)はhypomhからの出力のコピーです。
.LP
例は次のとおりです。
.LP
.nf
#p 980217.140302 Nikko hagiwara
#p 98 02 17 14 02 42
#p 0200 0 20 752 20 758 +1
#p 0200 3 20 800 20 800 -1 2.79e-06
#p 0201 1 21 911 21 923 +0
#p 0206 0 21 126 21 138 +0
#p 0206 3 22 520 22 520 -1 1.41e-06
#p 0208 1 22 494 22 512 +0
#p 020C 0 20 899 20 905 +1
#p 020C 3 20 990 20 990 -1 2.39e-06
#p 020E 1 22 126 22 138 +0
#p 0218 0 20 831 20 843 +0
#p 0218 3 20 890 20 890 -1 2.35e-06
#p 021A 1 22 126 22 138 +0
#p 0234 0 20 862 20 868 +1
#p 0234 3 20 910 20 910 -1 5.28e-06
#s 98/02/17 14:03                   98/02/17 14:18:04
#s ASO  U   2.755 0.003   3.917 0.006   0.0 2.79e-06   36.64934  139.45970    720
#s KBH  .   2.837 0.006   4.132 0.006   0.0 2.35e-06   36.65450  139.52824    750
#s NIK  U   2.865 0.003   0.000 0.000   0.0 5.28e-06   36.62144  139.49072   1310
#s KRO  U   2.902 0.003   4.132 0.006   0.0 2.39e-06   36.68685  139.49794    865
#s GNZ  .   3.132 0.006   4.503 0.009   0.0 1.41e-06   36.65316  139.41226    880
#s 
#f  98  2 17    14  3   1.174   36.64721  139.48737   8.048   0.7
#f    CONV              0.000    0.181      0.130     0.275
#f      0.017    -0.003     0.004     0.033     0.002     0.076
#f              36.600 100.0 139.500 100.0  30.000  30.0
#f    5  ERI  5 ( 18.0% )  4 ( 82.0% )  3 (  0.0% )
#f ASO  U    2.5 275.8 163.3  15.0  2.75 0.02  0.00  3.92 0.06  0.00 0.279E-05  0.6
#f KBH  .    3.7  77.3 155.6  21.9  2.84 0.02  0.00  4.13 0.06  0.09 0.235E-05  0.6
#f NIK  U    2.9 174.0 162.0  16.2  2.87 0.02 -0.01  0.00 0.00  0.00 0.528E-05  1.0
#f KRO  U    4.5  12.1 151.5  25.4  2.90 0.02 -0.01  4.13 0.06 -0.04 0.239E-05  0.6
#f GNZ  .    6.7 275.7 140.5  34.9  3.13 0.02  0.02  4.50 0.07 -0.03 0.141E-05  0.5
#f                                             0.01             0.05
.fi
.LP
.B (1)#pで始まる行
.br
１行目には空白で区切られた３つの項目があって、それぞれ
.IP
.nf
(a)波形ファイルの名前
(b)験測者が付けたラベル（メモ）
(c)験測者名
.fi
.LP
です。(b)は、ない場合はそれぞれピリオド "." になります。pickファイルは、
かならず１つの波形ファイルに属します。winは、ある波形ファイルを開いた
ときに、それに属するpickファイルを見つける方法として、まず波形ファイル
の含む時間の中に含まれる名前を持つpickファイルを見つけ、さらにその
１行目を読んで、上の(a)が波形ファイル名と一致するかどうか確認します。
２行目は、波形ファイルの先頭の時刻の年月日時分秒です。この時刻が
３行目以降に書かれている相対時刻の基準になります。
３行目からは各行が１つの読み取り値（P,S,F,最大振幅のいずれか）を
表しています。"#p"の次の４桁はチャネル番号、次の数字は 0,1,2,3 で
それぞれ P, S, F, 最大振幅の読み取り値であることを表します。
次に２桁と３桁の数字が２組ありますが、これは読み取り値の範囲の
始めと終わりの時刻を、波形ファイルの先頭から数えた秒数で、
それぞれ秒とミリ秒で表したものです。たとえば
.IP
#p 0200 0 20 752 20 758 +1
.LP
の場合、チャネル0200で読み取ったP時刻の値は先頭から 20.752秒〜20.758秒
の範囲です。次の-2,-1,0,+1の数字は、Pの読み取り値の場合は初動極性を
-1,+1,0(読まれてない)で表し、最大振幅の場合は、-2,-1,0,+1 がそれぞれ
単位 m/s/s, m/s, m, "単位なし"を表します。読み取り値が最大振幅の場合
だけ、もう一つ右に最大振幅値が入ります。
.LP
なお、ここで「波形ファイルの先頭から数えた秒数」は、
2001.7以前の版のwinで作られた場合、
波形ファイル中に
実際に含まれる秒ブロックの数で数えられます。波形ファイル中で特定の
秒がまるまる(全チャネル)抜けている場合、抜けた秒は「先頭から数えた秒数」
の勘定に入らなくなり、「先頭から数えた秒数」と「先頭との時間差(秒差)」は
一致しません。
このため、波形ファイルがないと、pickファイルの"#p"行の値だけから正確に
読み取り値の時刻を求めることはできません。
2001.7以降の版のwinで作られてものは、「先頭からの秒数」は正しく先頭時
刻との時間差を表しますので、pickファイルの"#p"行の値だけから正確に
読み取り値の時刻を求めることが出来ます(win -x などでそのまま使えます)。
.LP
.B (2)#sで始まる行
.br
１行目は２行目以降の秒単位の到着時刻データの基準になる年〜分、および
右側にこのファイル（hypomhへの入力ファイル）を作った時刻が入ります。
２行目からは各行が１つの観測点の験測データで、左から、観測点コード、
P初動極性（データなしは "."）、P時刻(s)、P精度(s)、S時刻(s)、S精度(s)、
F-P時間(s)、最大振幅(m/sのときのみ書きだされる)、観測点緯度(度)、
経度(度)、高度(m)、Pの観測点補正(s)、Sの観測点補正(s)です。
PとSの観測点補正は、この値が到着時刻に加えらるもので、０のときには
省略されます。最後に空行（"#s"のみの行）が１行あります。
.LP
.B (3)#fで始まる行
.br
１行目は震源時・緯度(度)、経度(度)、深さ(km)・マグニチュード、
２行目は診断（"CONV"・"NOCN"・"DEEP"・"AIRF"ど）と結果の誤差
（秒および km単位）です。ただし震源時の誤差は常に０で意味がありません。
３行目は誤差共分散行列の６つの成分で、東をx、南をy、下をzに
とった km 単位の座標系で、Cxx,Cxy,Cxz,Cyy,Cyz,Czzの順です。
従って２行目の緯度・経度・深さの誤差の自乗が、それぞれ Cyy,Cxx,Czzに
なっているはずです。４行目は与えた初期震源の位置およびその不確定さ
で、緯度(度)・緯度の不確定さ(km)・経度(度)・経度の不確定さ(km)・
深さ(km)・深さの不確定さ(km)です。５行目は左から、観測点数、速度構造
モデル名、P時刻データの数、S時刻データの数、初期値データの数（これは
初期震源の座標なので常に３）で、括弧内はそれぞれのデータからの寄与の
割合がパーセントで示されています（ただしhypomhの作者によると
P,Sそれぞれのパーセント表示は問題があって、両者の和は信用できる、
とのこと）。
.br
６行目からは各観測点ごとの結果が観測点数だけあって、各行の内容は、
左から、観測点コード・P極性・震央距離(km)・観測点方位（北から東回り
(度））・射出角（下から(度））・入射角（下から(度））・観測点補正後の
P時刻(s)・P精度(s)・P時刻のO-C(s)・観測点補正後のS時刻(s)・S精度(s)・
S時刻のO-C(s)・最大振幅(m/s)・マグニチュードです。ただし、最大振幅
データがなくてF-P時間データがある場合には、最大振幅の代わりに
F-P時間(s)が表示されます。F-P時間の場合は一般に値が１以上になります
ので、値からこの判別は容易です。マグニチュードは、最大振幅データがある
場合は渡辺(1971)の式を、F-P時間データしかない場合は津村(1967)の式を、
それぞれ使って求められていて、値"9.9"はマグニチュード未決定の意味です。
最後の行は、P時刻のO-CとS時刻のO-Cのそれぞれの標準偏差(s)です。
震源がよく決まった場合は、各観測点のO-C時間が精度と同程度以下に
なっているはずです。
.SH 注意事項
"#s" および "#f" で始まる部分は、フォートランプログラム(hypomh)で
読み書きされるので、各項目は桁位置が固定であることに注意してください。
出力の際は、たとえば "5F7.3" 等
といった書式で出力されていますので、値によっては項目間の空白が
なくなってつながっていたり、値が "*******" になっていたりすることが
あります。
