.TH pick2pick 1W "2004.3.7" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
pick2pick - 他の波形ファイル用への pickfile の書換えフィルター
.SH 形式
pick2pick 
.I trgname YY MM DD hh mm ss
.LP
.SH 解説
pick2pick は、win の検測情報ファイル(pickfile(1W))を標準入力から読み込
み、波形ファイルの名前を
.I trgname
にし、波形ファイルの先頭時刻を
.I YY MM DD hh mm ss
に設定し、標準出力に書き出します。
.LP
pick2pick は pickfile(1W) の #p で始まる部分のみを書き換えるのみで、そ
の他はそのまま出力されます。
.LP

.SH バグ
pick2pick はあまりエラーのチェックをしていません。例えば、読み取り値の
範囲の始めが
.I trgname
に収まっているかどうかは先頭時刻よりチェックしていますが、終わりの方は
何もチェックしていません。
.LP
pickfile(1W)によれば、#p での時間は波形ファイルの先頭から数えた秒数で
あり、しかも、波形ファイル中に実際に含まれる秒ブロックの数で数えらる、
とあります。pick2pick を厳密に動かそうとすれば、元の波形ファイルと変換
先の波形ファイルの中身をチェックし、特定秒ブロックの抜けを把握しなけれ
ばなりませんが、そのようなことは行なっていません。
.SH 関連事項
pickfile(1W)
