.TH ras2lips 1W "2010.9.21" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
ras2lips - Sun Raster形式イメージからLIPS言語への変換フィルター
.SH 形式
ras2lips [
.I file ] ...
.LP
.SH 解説
ras2lips は、pmon(1W) の印刷出力などの、Sun Raster 形式の
イメージを、キャノンLIPS IV対応プリンターに出力するための
フィルターです。イメージの解像度は400dpiであることを仮定しています。
印刷できるイメージの大きさは最大4516ドット x 3136ドットです。
ras2lips は標準入力からイメージデータを読み込み、LIPSプリンターへの
出力データを圧縮形式で標準出力へ書き出します。ただし
.I file ...
を指定した場合は、データをファイルから読み込みます。
ファイルが複数ある場合は１ページに１ファイルずつ出力します。
このときプリンターに両面印刷機能があると、印刷は両面（つまり
片面に１ファイル）になります。
.LP
ras2lips はキャノン LBP-430 と LBP-450 のみでテストしてあります。
.SH オプション
.TP 
なし
.SH ソース
.TP
`ras2util.c'
.SH 関連事項
pmon(1W), lpf_lbpvf(1W), ras2rpdl(1W)
