.TH raw_raw 1W "2002.5.31" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
raw_raw - RAW 形式データからチャネルを選択
.SH 形式
raw_raw [\-\fBBg\fR]
.I inkey
.I outkey
.I shmsize
[
.I chfile
[
.I logfile
]]
.LP
.SH 解説
raw_raw は、キー
.I \ inkey
の共有メモリ・セグメントに巡回的に書き込まれている
win 形式のデータを読み込み、キー
.I \ outkey
で与えられる共有メモリ・セグメントに書き出します。
チャネルファイル
.I \ chfile
が与えられた場合は、その中にリストされたチャネルのデータだけが
書き出されます。ただしチャネルファイル名の先頭に '\-' を付けたときは、
そのファイルにリストされた以外の全チャネルのデータが書き出されます。
.I chfile
が与えられないか、または '\-' である場合は、
全チャネルが書き出されます。
キー
.I \ outkey
をもつ共有メモリ・セグメントが存在しない場合は、大きさ
.I \ shmsize
\ (KB) の共有メモリ・セグメントが作られます。すでに存在している場合は、
そのサイズが
.I \ shmsize
\ (KB) よりも小さいとエラーになります。
共有メモリ・キーは32ビットの整数値です。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられ、
指定しないとログ情報は標準出力に
送られます。ログファイルは書き込みのたび毎に
オープン／クローズされます。
.LP
チャネルファイルは、１行に１つずつ、16進数でチャネル番号を書
き並べたテキストファイルです。各行の先頭の項目だけが読まれ、
空白またはタブで区切られた以降の項目は無視されます。また先頭
が '#' である行も無視されます。
raw_raw プロセスは
ハングアップシグナルを受け取ると、チャネルファイルを読み直します。
.LP
共有メモリ
.I inkey
上の形式は、時間順整列されたもの(order(1W)参照)
でもされていないもの(recvt(1W)参照)
でもかまいません。共有メモリ
.I outkey
の形式は
.I inkey
と同じになります。
.LP
raw_raw は、引数なしで起動すると簡単な使用法を表示します。
.LP
.SH オプション
.IP "\fB\-g" 5
サンプリングレート 1Hz のチャネルのデータのみ、
値を４ビット右シフト(つまり1/16に)します。
これは明星電気製GTA-45Uの低速データ用です。
.IP "\fB\-B" 5
出力共有メモリに「ブロック末尾にもブロックサイズを
持つ形式」で書き込みます。これについては recvt(1W), order(1W) を
参照してください。
.SH ソース
.TP
`raw_raw.c'
.SH 関連事項
winformat(1W), order(1W), send_raw(1W)
