.TH raw_ch 1W "2000.4.7" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
raw_ch - RAW 形式データのチャネル番号を変換
.SH 形式
raw_ch
.I inkey
.I outkey
.I shmsize
[
.I chfile
[
.I logfile
]]
.LP
.SH 解説
raw_raw は、キー
.I \ inkey
の共有メモリ・セグメントに書き込まれている
win 形式のデータを読み込み、チャネル変換表ファイル
.I chfile
にしたがってチャネル番号を変換し、結果をキー
.I outkey
で与えられる共有メモリ・セグメントに書き出します。
チャネル変換表ファイル に書いてないチャネル番号は、変換せずにそのまま
出力されます。ただしチャネル変換表ファイル名の先頭に '-' を付けたときは、
変換表にあるチャネルのデータだけが書き出されます。
.I chfile
が与えられない(その場合は
.I logfile
は指定できません)か、または '-' である場合は、
無変換で全チャネルが書き出されます。キー
.I outkey
をもつ共有メモリ・セグメントが存在しない場合は、大きさ
.I shmsize
(KB)の共有メモリ・セグメントが作られます。
すでに存在している場合は、そのサイズが
.I shmsize
(KB)よりも小さいとエラーになります。共有メモリ・キーは32ビットの整数値
です。
.br
ログファイル名
.I logfile
を指定すると、ここに動作ログがとられ、
指定しないとログ情報は標準出力に送られます。ログファイルは書
き込みのたび毎にオープン／クローズされます。
.LP
チャネル変換表ファイルは、１行に１チャネル分ずつ、変換前のチャネル番号と
変換後のチャネル番号のペアを16進数で、空白またはタブで区切って書
き並べたテキストファイルです。各行の先頭から２項目だけが読まれ、
空白またはタブで区切られた以降の項目は無視されます。また先頭
が '#' である行も無視されます。
raw_ch プロセスはハングアップシグナルを受け取ると、チャネル変換表
ファイルを読み直します。
.LP
共有メモリ
.I inkey
上の形式は、時間順整列されたもの(order(1W)参照)でもされていないもの
(recvt(1W)参照)でもかまいません。共有メモリ
.I outkey
の形式は
.I inkey
と同じになります。
.LP
raw_ch は、引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース
.TP
`raw_ch.c'
.SH 関連事項
winformat(1W), order(1W), send_raw(1W)
