.TH recvstatus2 1W "2002.6.19" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
recvstatus2 - 白山WIN_UDP動作/設定ステータスパケットの受信
.SH 形式
recvstatus2 [\-\fBr\fR]
.I port
[
.I logdir
]
.LP
.SH 解説
recvstatus2 は、白山工業製データ変換装置LS-7000等から送信される、
動作ステータスパケット(パケット種類A8)と
設定ステータスパケット(パケット種類A9)を
UDPポート
.I \ port
で受信し、ディレクトリ
.I \ logfile
にファイルとして出力します。
.I \ logdir
が与えられない場合は標準出力に書き出します。
.I \ logdir
に生成されるファイルの名前は、動作ステータスについては
"M"+"チャネル番号"+".xml" (たとえば "M025C.xml")、
設定ステータスについては
"S"+"チャネル番号"+".xml" (たとえば "S025C.xml")
になります。これらのファイルは新たなステータスが受信される
たびに上書きされます。
.LP
LS-7000等では、出力パケットタイプとして"A0"を設定する必要があります。
recvstatus2 はパケットの再送要求を行いません。
recvstatus2 は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.IP \fB\-r 5
ステータスファイルを書き出すたびに、それらを同じディレクトリの
RCSファイルにチェックイン("ci -l -q")します。RCSファイルが
存在しなければ新規に作られます。
.SH ソース
.TP
`recvstatus2.c'
.SH 関連事項
rcs(1), ci(1)
