.TH recvt 1W "2002.1.11" "WIN SYSTEM" "WIN SYSTEM"
.UC 4
.SH 名称
recvt - IPによる win 形式データの受信
.SH 形式
.IP
.ti -7
recvt
[
.I \-an
] [
.I \-g group
] [
.I \-i interface
] [
.I \-m before
] [
.I \-p after
]
.I port
.I shmkey
.I shmsize
[
.I ctlfile
[
.I logfile
]]
.LP
.SH 解説
recvt は、自ホストの UDP ポート番号
.I \ port
に宛てて送られる win 形式の
データを受信し、キー
.I \ shmkey
で与えられる共有メモリ・セグメントに（巡回的に）書き込みます。
そのキーをもつ共有メモリ・セグメントが存在しない場合は、大きさ
.I \ shmsize
\ (KB) の共有メモリ・セグメントが作られます。すでに存在している場合は、
そのサイズが
.I \ shmsize
\ (KB) よりも小さいとエラーになります。
UDP ポート番号は16ビットの整数値、共有メモリ・キーは32ビットの
整数値です。制御ファイル
.I \ ctlfile
が与えられた場合は、その中にリストされたチャネルのデータだけが
受信されます。ただし制御ファイル名の先頭に '\-' を付けたときは、
そのファイルにリストされた以外の全チャネルのデータが受信されます。
.I ctlfile
が与えられないか、または '\-' である場合は、全チャネルが受信されます。
.br
制御ファイル
.I \ ctlfile
には、
１行に１チャネルずつ指定された16進数のチャネル番号、または
"+"か"\-"で始まるホスト制御行を書くことができます。
前者の行では空白またはタブで
区切られた左端の項目だけが読まれ、その行の以降の部分は読み飛ばされます。
後者の行は、
.nf
       -host   hostからのパケットは拒否する
       +host   hostからのパケットは受け入れる
       +       受け入れる
       -       拒否する
.fi
の形式で書かれたルールです。前者(チャネル番号のリスト)の行と後者
(ホスト制御のルール)の行は混在していてもかまいません。
後者については、パケットごとにルールを上から当てはめていき、
当てはまるルールがあったらそれが適用されます。最後まで当てはまるルールが
なかったら、受け入れます(つまり最後にはかならず "+" の行があるのと同じ)。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられ、指定しないとログ情報は標準出力に
送られます。ログファイルは書き込みのたび毎に
オープン／クローズされます。
.LP
recvt は、HUPシグナルを受けると制御ファイル
.I \ ctlfile
を読み直し、ログファイル
.I \ logfile
に送り元ホストごとの流量情報を書き出します。これには起動時、または
前回HUPシグナルを受けたときからの、
.br
.nf
  パケット数、バイト数、毎秒パケット数、毎秒バイト数
.fi
が含まれます。
.LP
recvt は、デフォールトで自ホストの内部時計よりも+/\-30分以上離れた時刻の
データパケットは受け付けません。したがって recvt を走らせる
ホストでは、時計をある程度正確に合わせておく必要があります。
.LP
recvt が受信するデータは、一般に記録の時間順に送られてくるとは
限りません。この場合、recvt が書き込んだ共有メモリ上でも、データは
時間順にはなりません。order(1W) はこれを時間順に並べ変えます。
.LP
recvt は引数なしで起動すると簡単な使用法を表示します。
.SH ネットワーク上の形式
データはネットワーク上を UDP/IP パケットで伝送されます。UDP パケットで
送られる内容は、
.nf

    (1)１バイトのパケット番号(0〜255)
    (2)１バイトの「元の」パケット番号(0〜255)
    (3)１バイトの識別コード(16進数で) "A0"
    (4)２バイトのブロックサイズ((4)〜(6)部分の合計バイト数)
    (5)６バイトの時刻ヘッダー（年〜秒、各１バイト、BCD形式）
         年の下２桁(00〜99)、月(01〜12)、日(01〜31)、
         時(00〜23)、分(00〜59)、秒(00〜59)
    (6)同一秒の１チャネル分以上のデータ（win形式）
    以降(4)〜(6)の繰り返し

.fi
で、これは通常 send_raw(1W)ファミリ(send_raw, sendt_raw, send_mon, 
sendt_mon)が送信したり、それをrelay(1W)が中継して来るものです。
(1)は送信元ポートが
各パケットにつける、１ずつ増える番号です（255の次は0に戻ります）。
(2)には通常(1)と等しい値が入っていますが、再送パケットの場合には、
(2)には再送要求された元のパケットの番号が入っていて、それが
再送パケットであることを示します。
１パケットのサイズは1472バイト以内（IPパケットサイズで1500バイト
以内）で、伝送効率のため、通常は
なるべく大きくなるように上記(4)〜(6)の部分を次々に追加して
生成されます。なお、recvt は互換性のために、１パケットに１秒分しか
収容しない旧型のパケット形式
.nf

    (1)１バイトのパケット番号(0〜255)
    (2)１バイトの「元の」パケット番号(0〜255)
    (3)６バイトの時刻ヘッダー（年〜秒、各１バイト、BCD形式）
         年の下２桁(00〜99)、月(01〜12)、日(01〜31)、
         時(00〜23)、分(00〜59)、秒(00〜59)
    (4)１チャネル分以上のデータ（win形式）

.fi
も受け入れることができます。
.SH 再送プロトコル
送信側は発生したデータを上記の形式で UDP パケットに入れて
送り出し、基本的に流量制御は行ないません。受信側は送信元
（ホストとポートの組）ごとにパケット番号を
監視していて、欠落したパケットの番号を送信元ポートに送ることによって、
そのパケットの再送を要求します。再送要求パケットは、再送して欲しい
パケット番号だけを内容とする長さ１バイトの UDP パケットです。
送信元は再送要求されたパケットを
送り直します。通常の実装では、送信プロセスは過去最大128パケット
まで遡った再送に応え、受信プロセスは最大64パケットの連続した
欠落までを再送要求します。recvt はパケット番号の連続性を監視して
再送要求を行なう相手先として、100ヶ所までの送信元を認識することが
できます。100ヶ所を超えると、recvt は送信元テーブルを一旦白紙に戻し、
改めて登録を始めます。
.SH 共有メモリ上の形式
recvt が共有メモリに書き込むデータは、１秒分ずつのブロック形式です。
１ブロックの構造は次のようになっています。
.nf

    (1)４バイトのブロックサイズ（バイト）
    (2)４バイトの「書き込み時刻」
    (3)６バイトの時刻ヘッダー（年〜秒、各１バイト、BCD形式）
         年の下２桁(00〜99)、月(01〜12)、日(01〜31)、
         時(00〜23)、分(00〜59)、秒(00〜59)
    (4)同時刻の１チャネル分以上のデータ（win形式）

.fi
(2)は1970年1月1日0時から数えた秒数で示され、order(1W) が
データを時間順に整列させるときに、タイムアウトを設定するのに
利用されます。共有メモリ
・セグメント全体は、次のような構造体になっています。
.nf

   struct Shm {
     unsigned long p;         /* write point */
     unsigned long pl;        /* write limit */
     unsigned long r;         /* latest */
     unsigned long c;         /* counter */
     unsigned char d[SIZE];   /* data buffer */
     } *sh;

.fi
p, pl, r, c は管理用の変数、d がデータの領域で、これらはすべて
１つの書き込み側プロセスによって書き込まれます。読み出し側プロセスは
これらの変数を使って同期をとって、データを読み出します。
.TP
p
現在書き込み中のブロックの先頭位置（d の先頭からのバイト数）。
.TP
pl
ここを越えては新しい秒ブロックに入らず、先頭に戻る位置（d の先頭から
のバイト数）。これは共有メモリセグメントの大きさの90%の位置に
とられます。最後の秒ブロックはこの位置を越えて書き込まれますが、
そのブロックは、共有メモリセグメントの終端までには終わらなければ
なりません。したがって、共有メモリセグメントの大きさは、少なくとも、
最大の１秒ブロックの大きさの10倍以上である必要があります。
.TP
r
最後に書き込み完了したブロックの先頭位置（d の先頭から
のバイト数）。
.TP
c
これまでに書き込んだブロック数の積算値。
.LP
recvt は、連続して受け取ったデータパケットの
時刻が同じである限り、共有メモリ上の１つのデータブロックを
拡張していきます。従って受信したパケットと共有メモリ上のデータ
ブロックは必ずしも１対１には対応せず、同じ時刻の複数のパケットは、
１つのデータブロックにまとめられます。
.SH オプション
.IP \fB\-a 5
"A1"以上の種別コードをもつパケットも受け入れます。"A1"以上の
種別コードのパケットの場合は、種別コードもそのまま共有メモリに
コピーされ、共有メモリ上の形式は recvs(1W) に説明されるものに
なります。このとき、タイムスタンプまではチェックされますが、
それ以降のデータ部分のチェックされず、そのまま共有メモリに
コピーされます。チャネルによる選択は行なわれません。また、
同一タイムスタンプをもつ複数のパケットが1つにまとめられることはなく、
受信された1つのパケットは、共有メモリ上でも必ずタイムスタンプ付き     
の1つのブロックになります。"A1"以上の種別コードをもつパケットを
受信するはずのない場合は、不正な(壊れた)パケットを判別しやすく
するために、このオプションをつけない方が安全です。
.IP "\fB\-i \fIinterface" 5
IPマルチキャストアドレスに対して送信されるパケットを受信する場合に、
パケットを受信するネットワークインターフェースを、そのインターフェースの
IPアドレス
.I interface
で指定します。
.IP "\fB\-g \fIgroup" 5
IPマルチキャストアドレス
.I group
に対して送信されるパケットを受信します。
.IP "\fB\-m \fIbefore" 5
マシンの内部時計の時刻よりも before分だけ前の(遅れた)タイムスタンプを
もつパケットまで受け入れます。デフォールトは30分です。
.IP "\fB\-n \fIbefore" 5
拒否すべき送り元アドレスからのパケット、重複して受信した再送パケット、
不正なチャネルヘッダーをもつパケット、不正(許容時間範囲外を含む)な
タイムスタンプをもつパケットについての情報をログに報告しません。
.IP "\fB\-p \fIafter" 5
マシンの内部時計の時刻よりも after分だけ後の(進んだ)タイムスタンプを
もつパケットまで受け入れます。デフォールトは30分です。
.SH ソース
.TP 
`recvt.c'
.SH 関連事項
winformat(1W), send_raw(1W), sendt_raw(1W), send_mon(1W),
sendt_mon(1W), relay(1W)
