.TH recvstatus 1W "2002.6.19" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
recvstatus - 明星GTA-45Uステータスパケットの受信
.SH 形式
recvstatus
.I port
[
.I logfile
]
.LP
.SH 解説
recvstatus は、DOSベースのGTA-45U HDLCフレームパケット受信プログラム
hdlc から送信される、明星電気製テレメータ装置GTA-45Uのステータス
パケットをUDPポート
.I \ port
で受信し、ファイル
.I \ logfile
に書き出します。
.I \ logfile
が与えられない場合は標準出力に書き出します。
GTA-45Uの１バイトのステータス情報はすべてのHDLCフレームに
付加されており、hdlcはそれらをすべて送信してきますが、
recvstatus はそのステータスバイトに変化があったときだけ、
それを書き出します。
.I \ logfile
へ書き出す形式は次の例の通りです。
.LP
.nf
020619.093206 recvstatus 192.168.211.16:1031 16 020619 093202 0416 ... 00
.fi
.LP
上の内容は、左から、ログの年月日時分秒、プログラム名、ステータスを
送ってきたホストのIPアドレスとポート番号、観測点番号(チャネル番号の
下位１バイト、ステータスのタイムスタンプ(年月日、時分秒)、チャネル番号、
ステータスバイトです。ステータスバイトの各ビットの意味は
次の通りです。
.LP
.nf
 ビット     意味

   80     停電
   40     バッテリー降下
   20     GPS RX異常
   10     GPS INVALID
   08     閏秒(使われてない)
   04     GS CONT異常
   02     INTEL COM A 異常
   01     SPAD 異常
.fi
.LP
recvstatus は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP
なし。
.SH ソース
.TP
`recvstatus.c'
.SH 関連事項
winformat(1W)
