.TH relaym 1W "2004.11.11" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
relaym, relaymd - win 形式データのIP上の複数の宛先への中継
.SH 形式
relaym [\-\fBDnr\fR] [\-\fBb\fI bufsiz\fR] [\-\fBd\fI\ delay\fR] [\-\fBf\fI ctlfile\fR]
.I inport
.I paramfile
[
.I logfile
]
.LP
relaymd [\-\fBnr\fR] [\-\fBb\fI bufsiz\fR] [\-\fBd\fI\ delay\fR] [\-\fBf\fI ctlfile\fR]
.I inport
.I paramfile
[
.I logfile
]
.SH 解説
relaym は、自ホストの UDP ポート番号
.I \ inport
に送られてくる win 形式のデータを受信し、パラメータファイル
.I \ paramfile
に記述されたホストへ送信します。
relaym は受信したパケットのパケット番
号を検査しますがタイムスタンプは検査しません。
.LP
IPv4、 IPv6 双方のアドレスを同時に扱うことができます。
.LP
relaymd は daemon モードで起動します。relaym でオプション
\fB\-D\fR
を指定した時と同じ動作です。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられます。
指定しないとログ情報は標準出力に
送られます(ただし、daemon モードで動いている時は syslogd(8) に送られま
す)。ログファイルは書き込みのたび毎にオープン／クローズされます。
.LP
relaym は、HUPシグナルを受けると(もし指定されていれば後述の)制御ファイル
.I \ ctlfile
を読み直し、ログファイル
.I \ logfile
に送り元ホストごとの流量情報を書き出します。これには起動時、または
前回HUPシグナルを受けたときからの、
.br
.nf
  パケット数、バイト数、毎秒パケット数、毎秒バイト数
.fi
が含まれます。
.LP
relaym は引数なしで起動すると簡単な使用法を表示します。
.SH パラメータファイルの形式
パラメータファイルは、１行に１つずつ、ホスト名(もしくはIPアドレス)とポー
ト番号(もしくはポート名)の組みを
書き並べたテキストファイルです。ホスト名とポート番号の間は空白かタブで
区切られなければいけません。それ以降の項目は無視されます。また先頭
が '#' である行も無視されます。128個の宛て先まで指定でき、それ以上は無
視されます。
.SH ネットワーク上の形式と再送プロトコル
recvt(1W)を参照してください。
relaym はパケット番号の連続性を監視して
再送要求を行なう相手先として、100ヶ所までの送信元（ホストとポート
の組）を認識することが
できます。100ヶ所を超えると、recvt は送信元テーブルを一旦白紙に戻し、
改めて登録を始めます。
.SH オプション
.IP "\fB\-b \fIbufsiz" 5
受信ソケットバッファサイズを
.I bufsiz
KBにします。ただしこれはシステムで許される値の範囲でなければ
なりません。デフォルトは256KBです。
.IP \fB\-D 5
daemon モードで起動します。
.IP "\fB\-d \fIdelay" 5
前のパケットを中継してから0.5秒以上経過した後に
パケットが届いたとき、そのパケットを送信する前に
.I delay
ミリ秒の遅延を挿入します。
.IP "\fB\-f \fIctlfile" 5
制御ファイル
.I \ ctlfile
で指定される、送信元ホストによる受信制御を可能にします。
.I \ ctlfile
には、"+"か"\-"で始まるホスト制御行を書くことができます。
各行では空白またはタブで区切られた左端の項目だけが読まれ、
その行の以降の部分は読み飛ばされます。'#'で始まる行はコメントと
見なされます。
.br
ホスト制御行は、
.nf

       -host   パケットがhostからであれば捨てる
       +host   パケットがhostからであれば受け入れる
       +       パケットを受け入れる
       -       パケットを捨てる

.fi
の形式で書かれたルールです。
ホスト制御については、パケットごとにルールを上から当てはめていき、
当てはまるルールがあったらそれが適用されます。最後まで当てはまるルールが
なかったらそのパケットを受け入れます(つまり最後にはかならず "+" の行が
あるのと同じ)。
.IP "\fB\-n" 5
拒否すべき送り元アドレスからのパケットや重複して受信した再送パケット
についての情報をログに報告しません。
.IP "\fB\-r" 5
再送要求パケットを送信しません。
DVB衛星配信ボードによる受信のような一方通行の伝送路の場合には、
これにより不要なパケット送信を抑制することができます。
.SH ソース 
.TP
`relaym.c daemon_mode.c win_log.c udp_accept.c udp_dest.c'
.SH 関連事項
winformat(1W), recvt(1W), send_raw(1W), order(1W), relay(1W)
