.TH select_stations 1W "2004.1.29" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
select_stations - チャネル表形式のファイルから任意の領域の観測点を選び出す
.SH 形式
select_stations
.I ch_file
.I polygon_file
.LP
.SH 解説
select_stations はチャネル表形式のファイル
.I \ ch_file
の中から、
.I \ polygon_file
で指定される多角形領域の内部に位置する観測点の行(チャネル)を
選び出して、標準出力に書き出します。ただし
.I \ ch_file
で緯度と経度が省略してあるチャネルは無視されます。
チャネル表ファイルの形式については win(1) を見てください。
.br
.I \ polygon_file
の形式は次の通りです。
多角形の頂点の座標(度単位の緯度と経度を空白またはタブで区切る)を
1行に1点ずつ、順に時計回りに羅列します。最後の頂点は最初の頂点と
一致させて多角形を閉じることが必要です。多角形の頂点は
外側に凹でもかまいません。
.LP
select_stations は領域を示す多角形の各辺を、
時計回りに順に調べていき、点から最も近い辺の
(始点から終点を見込んだ)右側に点がある場合に、
その点は多角形の内部にあると判断しています。
.LP
select_stations は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`select_stations.c'
.SH 関連事項
win(1W)
.SH バグ
初期のプログラム(1999.11.9版)にあった重大なバグは
2004.1.28版で修正されました。
