.TH shmdump 1W "1998.5.21" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
shmdump - 共有メモリ・セグメント上のデータのモニタ
.SH 形式
shmdump
.I shmkey
.SH 解説
shmdump は、キー
.I \ shmkey
で与えられる共有メモリ・セグメントに巡回的に書き込まれている
データの、各ブロックの最初の部分を読んでダンプしていきます。
１ブロック（１秒分）の情報が１行に表示されます。
shmdump は共有メモリ上のブロック形式として、「書き込み時刻」付きの
もの（recvt(1W)参照）および「書き込み時刻」無しのもの
（order(1W)参照）のどちらでも、自動的に判別して読むことができます。
表示形式は以下のとおりです。
.SH 「書き込み時刻」無しの場合
まずブロックサイズ（バイト）、次にタイムスタンプの時刻（年〜秒）を12桁で、
次に最初のチャネルブロックの先頭８バイトを16進数で表示します。
.SH 「書き込み時刻」付きの場合
まずブロックサイズ（バイト）、続いて「書き込み時刻(RT=RealTime)」を年〜秒の
12桁で、その後にそれとタイムスタンプの時刻(TS=TimeStamp)との差
(RT-TS)を秒単位で表示し、次にタイムスタンプの時刻(TS)を年〜秒の12桁で、
次に最初のチャネルブロックの先頭８バイトを16進数で表示します。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`shmdump.c'
.SH 関連事項
winformat(1W), recvt(1W), order(1W)
