.TH shmx 1W "2002.8.12" "WIN SYSTEM" "WIN SYSTEM" 
.SH ╠╛╛╬ shmx - WINе╖е╣е╞ер═╤ете╦е┐б╝е─б╝еы 
.SH ╖┴╝░
shmx
.I ch ch ... 
.LP
.SH ▓Є└т
shmx д╧бвshmdump -tq д╟╜╨╬╧д╡дьдые╟б╝е┐дЄ
╞■╬╧д╚д╖бве┴еуе═еыID
.I \ ch
д╦еъе╣е╚д╡дьд╞дддые┴еуе═еыдЄX▓ш╠╠╛хд╦╔╜╝ид╖д▐д╣бг
е┴еуе═еыд╧бв╔╜╝ид╖д┐дд16┐╩┐Їд╬е┴еуе═еы╚╓╣цд╟д╣бг
.LP
shmx д╧░·┐Їд╩д╖д╟╡п╞░д╣дыд╚┤╩├▒д╩╗╚═╤╦бдЄ╔╜╝ид╖д▐д╣бг
.SH еке╫е╖ечеє
.IP "\fB\-m\fImin" 5
1е╚еьб╝е╣д╦╔╜╝ид╣╗■┤╓дЄ╩мд╟╗╪─ъд╖д▐д╣бее╟е╒ейеые╚д╧1╩мд╟д╣бе 
.IP "\fB\-m\fInline" 5
1е┴еуе═еыдвд┐дъ╔╜╝ид╣дые╚еьб╝е╣┐Їбее╟е╒ейеые╚д╧6д╟д╣б
.IP "\fB\-y\fIpixel" 5
1е┴еуе═еыдвд┐дъд╦│╬╩▌д╣дые╘епе╗еы┐Їбее╟е╒ейеые╚д╧12д╟д╣бе
.IP "\fB\-w\fIcliplevel" 5
епеъе├е╫еье┘еыдЄ╗╪─ъд╖д▐д╣бее╟е╒ейеые╚д╧+-yLSBд╟д╣.
.IP "\fB\-l\fIlta" 5
еке╒е╗е├е╚╩мдЄ░·дп╛ь╣чд╦▓┐╔├д╬е╟б╝е┐дЄ╩┐╢╤д╖д╞░·дпдлдЄ╗╪─ъд╖д▐д╣бее╟е╒ейеые╚д╧1╔├д╟д╣бе
.IP "\fB\-p" 5
╔╕╜р╞■╬╧дЄ╔╕╜р╜╨╬╧д╪╜╨╬╧д╖д▐д╣бе
.IP "\fB\-x\fIwidth" 5
1е╚еьб╝е╣д╬X╩¤╕■д╬е╘епе╗еы┐Ї. е╟е╒ейеые╚д╧800д╟д╣бе
.IP "\fB\-c\fIcolor" 5
╔╕╜рд╟д╧╟Єд╟е╫еэе├е╚,-c1д╟└╓д╟╔╜╝и,-c3д╟└╓бд┐х┐збд▓л┐зд╬╜чд╟╔╜╝ид╖д▐д╣бе
.IP "\fB\-f\fIshmdump.out" 5
е╒ебедеыshmdump.outдлдще╟б╝е┐дЄ╞╔д▀╣■дєд╟╔╜╝ид╣дыбе
.IP "\fB\-t\fItable" 5
WINд╬е┴еуе═еые╟б╝е╓еыдЄ╞╔д▀╣■д▀д▐д╣бе┤╤┬м┼└╠╛дкдшд╙└о╩м╠╛дЄ╔╜╝ид╣дыдшджд╦д╩дъд▐д╣бе
.SH е╜б╝е╣ 
.TP
`shmx2'
.SH ┤╪╧в╗Ў╣р
shmdump(1W), shmx(1W)
