.TH split_win 1W "2010.8.13" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
split_win - win 形式ファイルを時間不連続のある場合分割する
.SH 形式
split_win [\-\fBv\fR] [\-\fBa\fI suffix_length\fR]
[
.I file
[
.I name
]]
.LP
.SH 解説
split_win は、win 形式ファイル
.I \ file
に時間不連続がある場合，不連続の部分で分割します。
.I \ file
が単一のダッシュ('-')または無い場合、標準入力から読み込みます。

オプションのあとに引数を指定した場合、最初の引数は入力ファイルの名前と
して扱われます。その次の引数は、分割したデータを格納するファイル名の接
頭語として扱われます。この場合、分割したデータを格納するファイル名は接
頭語のあとに ``a-z'' の範囲の
.I suffix_length
個の文字を付けたファイルに、辞書式順序で分割されます。
.I -a
が指定されない場合、2 文字が接尾語として使用されます。

.I name
引数が指定されなかった場合、分割されたデータ名は、接頭語が 'W' となり、
前述の接尾語が付きます。

split_win は
.I -h
オプションで起動すると簡単な使用法を表示します。
.SH オプション
.IP "\fB\-a" 5
.I suffix_length
文字を、ファイル名のサフィックスの生成に使用します。
.IP "\fB\-v" 5
冗長な出力になります。
.IP "\fB\-h" 5
簡単な使用法を表示します。
.SH ソース
.TP
`split_win.c'
.SH 関連事項
winformat(1W)
