.TH recvt 1W "2014.5.22" "WIN SYSTEM" "WIN SYSTEM"
.UC 4
.SH 名称
vanpro2 - 気象計Vantage Pro2からUDP/IP経由でのデータ受信
.SH 形式
.IP
.ti -7
vanpro2
[
.I \-s 4|5|5f
] [
.I \-g mcast_group
] [
.I \-i interface
] [
.I \-s itvl
]
.I remIP:port
.I myport
.I ch_base
.I shmkey
.I shmsize
[
.I logfile
]
.LP
.SH 解説
vanpro2 は、IPアドレス
.I remIP
、自身の受信用UDPポート番号
.I \ port
であるようなシリアル／IP変換器(例えばMOXA NPort5110)
に接続された気象計 Vantage Pro2 から毎秒データを
送らせてUDPポート番号
.I myport
で受信し、１秒１パケット(サンプリングレート1Hz)のWIN形式に変換してキー
.I \ shmkey
で与えられる共有メモリ・セグメントに（巡回的に）書き込みます。
タイムスタンプは受信ホストのシステム時計で付けられます。
WIN形式で出力されるデータは次の11項目です。
.nf

  気圧(単位hPa)、屋内温度(0.1℃)、屋内湿度(%)、屋外温度(0.1℃)、
  風速(0.1m/s)、10分平均風速(0.1m/s)、風向(北から右回りの°)、
  屋外湿度(%)、雨量(0.1mm/hour)、日雨量(0.1mm)、電源電圧(0.01V)

.fi
WIN形式データ(整数値)の単位は、上記の各括弧内の通りです。
WIN形式についてはwinformat(1W)を、
共有メモリ上のフォーマットについてはrecvt(1W)を参照してください。
WIN形式のチャネル番号は、
.I \ ch_base
から上記の順に割り振られます。
キー
.I \ shmkey
をもつ共有メモリ・セグメントが存在しない場合は、大きさ
.I \ shmsize
\ (KB) の共有メモリ・セグメントが作られます。すでに存在している場合は、
そのサイズが
.I \ shmsize
\ (KB) よりも小さいとエラーになります。
UDP ポート番号は16ビットの整数値、共有メモリ・キーは32ビットの
整数値です。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられ、
指定しないとログ情報は標準出力に
送られます。ログファイルは書き込みのたび毎に
オープン／クローズされます。
.LP
vanpro2 は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.IP "\fB\-b \fImode" 5
書き込みデータのサンプルサイズが
.I 4 バイト
の場合のサンプルサイズ情報のモードを指定します。
.nf
4 : サンプルサイズ情報を 4 にします。
5 : サンプルサイズ情報を 5 にします。
5f : サンプルサイズが 4 バイト長以外についてもサンプルサイズ情報を 5
     にします。つまり、常に圧縮の無い固定長データとなります。
.IP "\fB\-g \fIgroup" 5
IPマルチキャストアドレス
.I group
に対して送信されるパケットを受信します。
.IP "\fB\-i \fIinterface" 5
パケットを受信するネットワークインターフェースを、そのインターフェースの
IPアドレス
.I interface
で指定します。
.IP "\fB\-s \fIitvl" 5
.I \ itvl
WIN形式のデータ出力とは別に、データをテキスト形式で
ログファイルに書き出す間隔を、
分単位で指定します。デフォルトは 0 で、その場合は
起動時に一度だけ、データがログファイルに書き出されます。
形式は次の例のようなものです。
.nf

120423.183827 vanpro2 baro=1008 t_in=261 h_in=35 t_out=165 w_sp=31 w_av=40 w_dir=329 h_out=57 r_rate=0 r_day=0 batt=478
.fi
.SH 実行例
.nf

vanpro2 -s 60 192.168.209.104:50000 9001 f000 101 100

.fi
シリアル／IP変換器のIPアドレスとUDPポートは
192.168.209.104と50000、送られて来るデータの
宛先(受信)ポートは 9001で、WIN形式データにはF000から
11個のチャネル番号が付与されます。出力の共有メモリ
キーは 101、サイズは100KBです。ログファイルにも
60分に１回、テキスト形式でデータを出力します。
各データ項目のチャネル番号は、起動時に書き出される
.nf

120423.183826 vanpro2   baro[F000] t_in[F001] h_in[F002] t_out[F003] w_sp[F004] w_av[F005]
120423.183826 vanpro2   w_dir[F006] h_out[F007] r_rate[F008] r_day[F009] batt[F00A]

.fi
のようなログでも確認できます。
.SH ソース
.TP
`vanpro2.c'
.SH 関連事項
winformat(1W), recvt(1W)
