.TH wadd 1W "1995.7.14" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wadd - 時間の重なった２つの win 形式ファイルの結合
.SH 形式
wadd
.I mainfile
.I subfile
[
.I outdir
]
.LP
.SH 解説
wadd は、win 形式ファイル
.I \ mainfile
に、
win 形式ファイル
.I \ subfile
を付け加えて、結果を
.I \ mainfile
と同じ名前で
.I \ outdir
で指定されたディレクトリに入れます。
.I \ outdir
が指定されないと、結果は
.I \ mainfile
を置き換えます。結果のファイルの時間範囲は
.I \ mainfile
のそれと一致します。
.I \ subfile
の中で、
.I \ mainfile
と同じチャネル番号のデータは無視されます。すなわち、
.I \ subfile
のうち
.I \ mainfile
と時間範囲が重なっていて、チャネル番号の異なる部分だけが、
.I \ mainfile
に付け加えられます。
.LP
wadd は win 形式波形ファイルと同じディレクトリで、
波形ファイル名に '.ch' を付け加えたファイルを、
そのチャネル表ファイルであると見なして、チャネル表ファイルも
波形ファイルと同様にして、結果ファイル名に '.ch' を
付け加えたファイル名として合成します。もしチャネル表ファイルが
見つからない場合は、結果のチャネル表ファイルは作られません。
.LP
.I subfile
に
.I \ mainfile
の開始時刻（第１秒）のデータが含まれていない場合、wadd は
結果のファイルの第１秒分の中に、
.I \ subfile
が含むチャネルのダミーデータを挿入します。これは、
win(1W) プログラムが第１秒分中に含まれないチャネルを、以降で
無視してしまうことに対応するためです。
.LP
同じチャネル構成をもち、時間範囲が前後する２つの win 形式
ファイルを連結するには、 cat(1) が利用できます。
.LP
wadd は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`wadd.c'
.SH 関連事項
win(1W), wed(1W), wck(1W), winformat(1W)
