.TH wch 1W "1997.6.20" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wch - win 形式ファイルのチャネルでの選択フィルター
.SH 形式
wch
.I chfile
.LP
.SH 解説
wch は、標準入力から与えられた win 形式ファイルを
入力とし、チャネルファイル
.I \ chfile
にリストされているチャネルだけを切り出して
標準出力にコピーします。
チャネルファイルは、切り出したい16進数のチャネル番号を
１行に１つずつ書いたテキストファイルです。各行内では、空白またはタブ
で区切られた先頭の項目だけがチャネル番号として読まれ、残りの
部分は無視されます。
.LP
wch は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`wch.c'
.SH 関連事項
wed(1W), win(1W), wck(1W), wadd(1W), winformat(1W)
