.TH wchasn 1W "2003.8.9" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wchasn - win 形式ファイルのチャネル番号強制割り当てフィルター
.SH 形式
wchasn
.I ch
.LP
.SH 解説
wchasn は、標準入力から与えられた win 形式ファイルを
入力とし、1秒ブロックの中に含まれるチャンネルの数だけ16進数のチャネル番号
.I \ ch
からインクリメントさせて順番に割り振っていき、標準出力に出力します。各
秒ブロックでのデータの並びが同じであることを想定しています(つまり、
例えば上下動成分のデータが1番目、南北成分のデータが2番目、東西成分のデー
タが3番目にデータファイル中で必ず並んでいること)。
.LP
wchasn は引数なしで起動すると簡単な使用法を表示します。
.SH 注意
チャンネル番号の変更が目的であるならば wchch(1W) を使うべきで、自分が
何をしようとしているのか理解していない場合はこのコマンドを使用すべきで
はありません。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`wchasn.c'
.SH 関連事項
wchch(1W), wch(1W)
