.TH wchch 1W "1997.12.4" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wchch - win 形式ファイルのチャネル番号変更フィルター
.SH 形式
wchch
.I chfile
.LP
.SH 解説
wchch は、標準入力から与えられた win 形式ファイルを
入力とし、チャネルファイル
.I \ chfile
に変更前後のチャネル番号がリストされているチャネルについては
そのとおりにチャネル番号を変更し、それ以外のチャネルについては
そのまま、標準出力にコピーします。
チャネルファイルは、
１行に１チャネル分ずつ、変更前と変更後のチャネル番号のペアを
空白またはタブで区切って、16進数で書いたテキストファイルです。
各行内では先頭から２項目だけが変更前後のチャネル番号として読まれ、
残りの部分は無視されます。
.LP
wchch は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`wchch.c'
.SH 関連事項
wch(1W), wed(1W), win(1W), wck(1W), wadd(1W), winformat(1W)
