.TH wck 1W "2000.8.14" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wck - win 形式ファイルの内容の検査
.SH 形式
wck [ \-rmhctu ] [ 
.I file [
.I position
]]
.LP
.SH 解説
wck は、win形式ファイル
.I file
の内容の概略を表示します。wck はファイル
.I file
を読み、先頭の第１秒分を構成する各チャネルについて、チャネ
ル番号（16進数）、サンプリングレート (Hz)、サンプルサイズ（バイト、
ただし win2形式の場合はビット）、チャネル・ヘッダーを含む
ブロックサイズ（バイト）を表示します。ただし整数値
.I position
が与えられた場合は、第１秒分の代わりに第(position+1)
秒分についての構成を表示します。このほか、ファイルの全長にわたり、
各秒について、時刻（年〜秒）、１秒分に含まれるチャネル
数と占める大きさ（バイト）を表示します。最後に、ファイルに含
まれる秒数とファイルの大きさ（バイト）を表示します。
.LP
.I file
が与えられないか、または "-" である場合は、wck は標準
入力からデータを読みます。出力は常に標準出力です。
.LP
wck は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
\-r
入力データがRAW形式のときに指定します。これがデフォールトです。
wck は win2形式に対応しています。
.TP 
\-m
入力データがMON形式のときに指定します。
.TP 
\-r
入力データが高サンプリングレート拡張のRAW形式のときに指定します。
.TP
\-u
簡単な使用法を表示します。
.TP
\-c
計数モード。入力に含まれるすべてのチャネルについて、秒数を表示します。
.TP
\-t
テーブルモード。チャネル番号の全スペース(0000〜FFFF)に
ついて、データの存否を表示します。入力ファイル中に1秒分でもあれば、
そのチャネルは「存」です。
１文字が16チャネル分(XXX0〜XXXF)の枠に対応し、その中でデータが存在した
チャネルの数(0〜16)を文字または記号(\- がゼロ、1〜9が文字通り1〜9、
A〜Gが10〜16の意味)表しています。1行で1024チャネル分、64文字を含み、
全体で64行になります。
.SH ソース 
.TP
`wck.c'
.SH 関連事項
win(1W), wed(1W), wadd(1W), winformat(1W)
