'\" t
.TH wdiskts 1W "2002.5.31" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wdiskts, wdisktsd - 「書き込み時刻」付 win 形式データのディスクファイルへの書き込み
.SH 形式
wdiskts
.I shmkey
.I outdir
[
.I nfiles
[
.I logfile
]]
.LP
wdisktsd
.I shmkey
.I outdir
[
.I nfiles
[
.I logfile
]]
.LP
.SH 解説
wdiskts は、キー
.I shmkey
の共有メモリ・セグメントに書き込まれている、
「書き込み時刻」付きの win 形式のデータを、ディスクのディレクトリ
.I outdir
の中に、win 形式のファイルとして書き込みます。1秒毎に共有メモリからメ
モリに読み込みます。ですので、読み
出し側の共有メモリの大きさは、1秒間で上書きされないだけの大きさを取る
必要があります。
分の値が変わった時に一気にディスクに書き込み、書き込みの際、パケットを
時間順に整列します。wdiskts では、ファイルは１分間分ずつ、'YYMMDDhh.mm'
の形式の名前をもつファイルにまとめられます。ファイル名はシステムの
時刻が用いられます。よって、システムの時刻が１分以上飛ぶと、ファイル名
が不連続になったり、書き込んだファイルを上書きすることがあります。
.I \ nfiles
は保存するべき最大のファイル数で、常時最新の
.I \ nfiles
個のファイルが保存され、それより古いファイルは消されていきます。
.I nfiles
を指定しないか、'0' を指定すると、ファイルを自動的に消すことは
しません。
.LP
wdisktsd はdaemon モードで起動します。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられ、指定しないとログ情報は標準出力に
送られます(ただし、daemon モードで動いている時は syslogd(8) に送られま
す)。ログファイルは書き込みのたび毎にオープン／クローズされます。
.LP
wdiskts は引数なしで起動すると簡単な使用法を表示します。
.SH 共有メモリ上の形式
recvt(1W) を参照してください。
\fB\-B\fR
オプションで書き込まれた形式はサポートしていませんので御注意下さい。
.SH ファイル
wdiskts は出力ディレクトリ
.I \ outdir
に次のようなテキストファイルを作り、
それぞれの内容によって動作状況を示します。

.RS
.TS
l l.
BUSY	現在書き込み中のファイル名
COUNT	現在のファイル数
LATEST	最も新しく書き込みの完了したファイル
MAX	保存すべきファイルの数
OLDEST	最も古いファイル名
.TE
.RE
.LP
wdiskts の動作中でもファイル MAX を書き換えると、それ以降は
「保存されるファイルの数」が新しい値に変わります。
.SH ソース 
.TP
`wdiskts.c'
.SH 関連事項
recvt(1W), order(1W)
