'\" t
.TH wdisk 1W "2002.5.31" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wdisk, wdisk60, wdiskd, wdisk60d - win 形式データのディスクファイルへの書き込み
.SH 形式
wdisk [\-\fBDns\fR]
.I shmkey
.I outdir
[
.I nfiles/freespace(-s)
[
.I logfile
]]
.br
wdiskd [\-\fBns\fR]
.I shmkey
.I outdir
[
.I nfiles/freespace(-s)
[
.I logfile
]]
.br
wdisk60 [\-\fBDns\fR]
.I shmkey
.I outdir
[
.I nfiles/freespace(-s)
[
.I logfile
]]
.br
wdisk60d [\-\fBns\fR]
.I shmkey
.I outdir
[
.I nfiles/freespace(-s)
[
.I logfile
]]
.LP
.SH 解説
wdisk、wdisk60、wdiskd、wdisk60d は、キー
.I \ shmkey
の共有メモリ・セグメントに書き込まれている、時間順に整列され
た win 形式のデータを、ディスクのディレクトリ
.I \ outdir
の中に、win 形式のファイルとして書き込みます。
.I \ shmkey
として '\-'を指定した場合は、入力データは共有メモリのかわりに
標準入力から読み込まれます。その場合の入力データの
形式は wdiskts(1W) の出力ファイルと同じです。
wdisk では、ファイルは
１分間分ずつ、'YYMMDDhh.mm' の形式の名前をもつファイルに
まとめられます。
wdisk60 では、ファイルは
１時間分ずつ、'YYMMDDhh' の形式の名前をもつファイルに
まとめられます。
.I \ nfiles
は保存するべき最大のファイル数で、常時最新の
.I \ nfiles
個のファイルが保存され、それより古いファイルは消されていきます。ただし、
オプション
\fB\-s\fR
を指定した場合は、常に確保すべきスペース(MB)を指定したことになります。
.I nfiles/freespace
を指定しないか、'0' を指定すると、ファイルを自動的に消すことは
しません。
.LP
wdiskd, wdisk60d は daemon モードで起動します。wdisk, wdisk60 でオプショ
ン
\fB\-D\fR
を指定した時と同じ動作です。
.LP
ログファイル名
.I \ logfile
を指定すると、ここに動作ログがとられます。
指定しないとログ情報は標準出力に
送られます(ただし、daemon モードで動いている時は syslogd(8) に送られます)。
ログファイルは書き込みのたび毎にオープン／クローズされます。
.LP
wdisk, wdisk60, wdiskd, wdisk60d は引数なしで起動すると簡単な使用法を
表示します。
.SH 共有メモリ上の形式
order(1W) を参照してください。
.SH オプション
.IP "\fB\-D" 5
daemon モードで起動します。
.IP "\fB\-s" 5
保存すべきファイルを、ファイル数ではなく、常に確保すべきスペースで指定
するようにします。MB 単位で第3引数に指定します。
.IP "\fB\-n" 5
次節に書いてある動作状況を示すファイルのうち、MAX を除く BUSY、COUNT、
LATEST、OLDEST のファイルを作りません。このオプションを指定した時は、
events(1W)、insert_raw(1W)、wtape(1W)といったこれらの動作状況を見るプ
ログラムは動かせません。
.SH ファイル
wdisk, wdisk60, wdiskd, wdisk60d は出力ディレクトリ
.I \ outdir
に次のようなテキストファイルを作り、
それぞれの内容によって動作状況を示します。
ただし、オプション \fB\-n\fR を指定した場合は MAX のみ作成します。

.RS
.TS
l l.
BUSY	現在書き込み中のファイル名
COUNT	現在のファイル数
LATEST	最も新しく書き込みの完了したファイル
MAX	保存すべきファイルの数/常に確保すべきスペース(MB)
OLDEST	最も古いファイル名
.TE
.RE
.LP
wdisk, wdisk60, wdiskd, wdisk60d の動作中でもファイル MAX を書き換える
と、それ以降は「保存されるファイルの数/常に確保すべきスペース(MB)」が
新しい値に変わります。
.SH ソース 
.TP
`wdisk.c'
.SH 関連事項
winformat(1W), order(1W), wtape(1W)
