.TH wed 1W "1995.7.14" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wed - win 形式ファイルの時間範囲とチャネルでの編集
.SH 形式
wed
.I date
.I time
.I length
[
.I chfile
]
.LP
.SH 解説
wed は、標準入力から与えられた win 形式ファイルを
入力とし、
.I \ date
と
.I \ time
で指示された時刻から
.I \ length
秒間のデータを切り出して標準出力にコピーします。
チャネルファイル
.I \ chfile
が指定されていれば、その中にリストされているチャネルだけが
切り出されます。
.I \ date
は年月日各２桁（計６桁）の数字で、
.I \ time
は時分秒各２桁（計６桁）の数字で指示します。
チャネルファイルは、切り出したい16進数のチャネル番号を
空白、タブまたは改行で区切って書き並べたテキストファイルです。
.LP
wed は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`wed.c'
.SH 関連事項
win(1W), wck(1W), wadd(1W), winformat(1W), wch(1W), wex(1W)
