.TH wex 1W "1997.6.20" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wex - win 形式ファイルの地域名による選択フィルター
.SH 形式
wex
.I zone ...
.LP
.SH 解説
wex は、標準入力から与えられた win 形式ファイルを
入力とし、引数として与えた地域名(
.I zone ...
)に含まれる観測点のチャネルだけを切り出して
標準出力にコピーします。
地域名の代わりに観測点名を与えてもいいですが、その場合は
その観測点を含む地域の観測点のチャネルがすべて出力されます。
.LP
地域名や観測点名からチャネル番号を得るために、wex はカレント
ディレクトリにある win.prm に指定されたチャネル表ファイルおよび
ゾーン表ファイルを利用します。win.prm が見つからないときは、
それぞれ /dat/etc/channels.tbl と /dat/etc/zones.tbl を
使おうとします。
.LP
wex は wch(1W) を利用したシェルスクリプトです。
.SH オプション
.TP 
なし
.SH ソース 
.TP
`wex'
.SH 関連事項
wch(1W), wed(1W), win(1W), wck(1W), winformat(1W)
