.TH winadd 1W "2010.9.16" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
winadd - win 形式ファイルの結合
.SH 形式
winadd [ \-fhmnsv ] 
.I file file ...
.LP
.SH 解説
winadd は、win形式ファイル
.I file
を結合し，標準出力に出力します．同じ時刻に同じチャンネルのデータがある
場合，引数の前にある
.I file
の物が優先されます．
.LP
winadd は最初すべてのデータをメモリに読み込もうとします(メモリモード)．メ
モリに展開出来ない場合はディスク上から読取ります(ファイルモード)．その
場合，実行速度がかなり遅くなるでしょう．
.LP
開始時刻（第１秒）にデータが含まれていないチャンネルがあった場合，
winadd は第１秒の中にこのチャンネルのダミーデータを挿入します．これは，
win(1W) プログラムが第１秒分中に含まれないチャネルを，以降で無視してし
まうことに対応するためです．また，時刻のジャンプがある所でもダミーデー
タを挿入します．これは，win(1W)プログラムでモニタ画面で時間のジャンプ
があることを分りやすくするためです．
.LP
winadd は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.TP 
\-f
ファイルモードだけで実行します。ほとんどの場合、実行速度が遅くなるでしょう。
.TP 
\-m
メモリモードで実行出来なかった場合、ファイルモードに移行しないで終了し
ます。
.TP 
\-n
すべてのダミーデータ付加しません．
.TP 
\-s
チャネル番号でソートします。
.TP 
\-v
コマンドの実行中、冗長です。
.TP
\-h
簡単な使用法を表示します。
.SH ソース 
.TP
`winadd.c'
.SH 関連事項
win(1W), wadd(1W), winformat(1W)
