.TH winform 1W "2015.12.28" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
winform - win 形式データへの変換 (obsoleted)
.SH 形式
.nf
WIN_bs winform(inbuf,outbuf,sr,ch)
int32_w *inbuf;
uint8_w *outbuf;
WIN_sr  sr;
WIN_ch  ch;
.fi
.SH 解説
この関数は古い仕様の関数です。今後は mk_windate(1W) を使用して下さい。
.PP
.I winform
は、４バイト整数配列
.I \ inbuf
に入れられた１秒分のデータを、win フォーマットの
チャネルブロックに変換して
.I \ outbuf
に入れられます。
.I \ sr
は渡されるデータの個数、すなわちサンプリングレートです。
.I \ ch
には16ビットのチャネル番号を指定します。
.LP
.I winform
は、チャネルヘッダー部分を含む、チャネルブロックの大きさ
（バイト）を返します。
.LP
.I \ inbuf
は作業領域として使われるため、内容が書き換えられることに注意してください。
.SH ソース 
.TP
`winlib.c'
.SH 関連事項
winformat(1W), mk_windata(1W), win2fix(1W)
