.TH wintosac 1W "2002.8.12" "WIN SYSTEM" "WIN SYSTEM" 
.SH 名称 
wintowin - WIN テキストフォーマット -> WIN フォーマット 変換ツール
.SH 形式
wintowin
.I (-h) <[in_file] >[out_file] or [shm_key] [shm_size]
.LP
.SH 解説
wintowin は、shmdump -tq で出力されるデータを入力として WINフォーマット
の波形データを出力します．あるいは，shm_key で指定された共有メモリに書き込みます．
.SH オプション
.IP -h
wintowin の簡単な利用法を出力します．
.SH 使用例
.nf
shmdump -B0.02:0.05:0.07:0.5:5.0 -tq 12 0252 | wintowin | win2raw /dat/bpf
チャネル0252に対してバンドパスフィルターをかけて，/dat/bpf に分ファイルとして
保存

shmdump -tq 12 0252 | wintowin 12 64
チャネル0252を共有メモリ12に書き込む
.SH ソース 
.TP
`wintowin'
.SH 関連事項
shmdump(1W)
