.TH wintosac 1W "2002.8.12" "WIN SYSTEM" "WIN SYSTEM" 
.SH 名称 
wintowin - WIN テキストフォーマット -> WIN フォーマット 変換ツール
.SH 形式
wintowin
.I (-h) <[in_file] >[out_file]
.LP
.SH 解説
wintowin は、shmdump -tq で出力されるデータを入力として WINフォーマット
の波形データを出力します．
.SH オプション
.IP -h
wintowin の簡単な利用法を出力します．
.SH ソース 
.TP
`wintowin'
.SH 関連事項
shmdump(1W)
