.TH wshift 1W "2014.1.8" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wshift - RAW 形式ファイルデータを任意ビット数右シフト
.SH 形式
wshift
.I bits
[
.I chfile
]
.LP
.SH 解説
wshift は、raw_shift(1W)のオフラインバージョンであり、標準入力から RAW 形式のデータを読み込み、全チャネルの全サンプルを
.I \ bits
ビットだけ右シフトして、
標準出力に書き出します。
ただしチャネルファイル
.I \ chfile
が与えられた場合は、その中にリストされたチャネルのデータだけが
シフトして書き出され、それ以外のチャネルは無視されます。
またチャネルファイル名の先頭に '\+' を付けたときは、
そのファイルにリストされたチャネルがシフトして書き出され、
それ以外のチャネルはそのまま出力にコピーされます。
さらにチャネルファイル名の先頭に '\-' を付けたときは、
そのファイルにリストされたチャネルはそのまま出力にコピーされ、
それ以外のすべてのチャネルはシフトして書き出されます。
.LP
チャネルファイルは、１行に１つずつ、16進数でチャネル番号を書
き並べたテキストファイルです。各行の先頭の項目だけが読まれ、
空白またはタブで区切られた以降の項目は無視されます。また先頭
が '#' である行も無視されます。
.LP
wshift は、引数なしで起動すると簡単な使用法を表示します。
.LP
.SH 使用例
.TP 
wshift 4 < /dat/raw/05081711.30 > /dat/shift/05081711.30
.SH オプション
.TP
なし
.SH ソース
.TP
`wshift.c'
.SH 関連事項
winformat(1W), raw_shift(1W)
