.TH wtime 1W "2000.12.20" "WIN SYSTEM" "WIN SYSTEM"
.SH 名称
wtime - win 形式ファイルの時刻ずらしフィルター
.SH 形式
wtime
[
.I \-h hours
] [
.I \-s sec
]
.LP
.SH 解説
wtime は、標準入力から与えられた win 形式ファイルを
入力とし、指定された時間だけ時刻をずらして、標準出力に
書き出します。ずらす方向は「指定した時間がタイムスタンプに
加算される」方向です。したがって、タイムスタンプを進める
ときは正の時間を、遅らせる場合は負の時間を指定します。
.LP
wtimeはファイル全体の時刻をずらします。チャネル単位でずらす必要があるときは、
.LP
wch(1W) で分離して wadd(1W) でくっつける必要があります。
.br
wtime は引数なしで起動すると簡単な使用法を表示します。
.SH オプション
.IP \fB\-h [hours]\fP 5
ずらすべき時間 hours を時単位で与えます。hours は整数でなければ
なりません。
.IP \fB\-s [sec]\fP 5
ずらすべき時間 sec を秒単位で与えます。sec は実数でもかまいません。
ずらすのが半端な秒(整数でない)のときは、最初の１秒の頭にダミーデータがつき、
その分最後の１秒中の後ろの部分がカットされるので、
ファイルの秒数は変わりません。
.LP
\fB\-h\fP と \fB\-s\fP は同時に指定してもかまいません(和になります)。
.SH 使用例
タイムスタンプを9時間進めます(UT->JSTのときなど)。
.IP
wtime -h 9
.LP
タイムスタンプを1.234秒遅らせます。
.IP
wtime -s -1.234
.SH ソース 
.TP
`wtime.c'
.SH 関連事項
wch(1W), wadd(1W), winformat(1W)
