.TH raw_ch 1W "2000.4.7" "WIN SYSTEM" "WIN SYSTEM"
.SH NAME
raw_ch - Conversion of channel numbers of RAW format data
.SH SYNOPSIS
raw_ch
.I inkey
.I outkey
.I shmsize
[
.I chfile
[
.I logfile
]]
.LP
.SH DESCRIPTION
Raw_raw loads win format data written in a shared memory segment identified by a key
.I \ inkey
and converts their channel numbers according to a channel conversion table
.I chfile
to write the results to another shared memory segment identified by another key
.I outkey.
Any channel numbers unlisted in the channel conversion table will be written unconverted. If the channel conversion table file name is prefixed with '-,' however, only the data of the channels listed in the conversion table will be written.
If
.I chfile
is not given (and hence
.I logfile
cannot be specified) or if '-' is specified as the channel conversion table, all the channels will be written unconverted. If the shared memory segment with the key
.I outkey
does not exist, a shared memory segment with a size of
.I shmsize
(KB) will be created.
If it already exists but has a size smaller than
.I shmsize
(KB), an error will occur. The shared memory key is a 32-bit integer.
.br
When log file name
.I \ logfile
is specified, operation log is set here. When it is not specified, log information is sent to the standard output. The log file is opened/closed in each write.
.LP
The channel conversion table file is a text file that hexadecimally lists pairs of pre- and post-conversion channel numbers, each pair delimited by a blank or tab, on a one-channel-one-line basis.
In each line, only the first and second items are read, while the subsequent items delimited by blanks or tabs are all bypassed. Any lines starting with '#' are also bypassed.
When receiving a hang-up signal, the raw_ch process rereads the channel conversion table.
.LP
The format in the shared memory
.I inkey
can be either one sorted in order of time (Cf. order(1W)) or otherwise (Cf. recvt(1W)). The format in the shared memory
.I outkey
will be the same as that of
.I inkey.
.LP
When raw_ch is initiated without argument, brief usage is displayed.
.SH OPTIONS
.TP 
None
.SH SOURCE
.TP
`raw_ch.c'
.SH SEE ALSO
winformat(1W), order(1W), send_raw(1W)
