#!/bin/sh
#
# $Id: _bj,v 1.2.4.1 2010/12/28 12:55:38 uehira Exp $
# _bj 98.6.10
#
if [ -f "$1" ]
then
  . $1
else
  . win.conf
fi
#
while true
do
        _update $PUSH
        newym
        sleep 60
done
