#! /bin/sh
#
# $Id: _find,v 1.1.4.1 2010/12/28 12:55:39 uehira Exp $
#
pid=`ps -agxw | cut -c-6,18- | awk '$3 ~ /(^|\/)'$1'$/{print $1}'`
if [ -n "$pid" ]
then
	echo \"$1\" pid=$pid
else
	echo \"$1\" is not running
fi
