#! /bin/sh
#
# $Id: _stop,v 1.2 2000/04/30 10:10:37 urabe Exp $
#
pid=`ps -agxw | cut -c-6,18- | awk '$3 ~ /(^|\/)'$1'$/{print $1}'`
if [ -n "$pid" ]
then
	/bin/kill -STOP $pid
	echo \"$1\" stopped
else
	echo \"$1\" is not running
fi
