#! /bin/sh
#
# $Id: _stop,v 1.2.4.1 2010/12/28 12:55:39 uehira Exp $
#
pid=`ps -agxw | cut -c-6,18- | awk '$3 ~ /(^|\/)'$1'$/{print $1}'`
if [ -n "$pid" ]
then
	/bin/kill -STOP $pid
	echo \"$1\" stopped
else
	echo \"$1\" is not running
fi
