#!/bin/sh
# check_status_sh   1999.8.16 urabe, 2002.2.14
#
host=`hostname -s`
echo -n $host 'GTA-45U last status report at '
date +'%y/%m/%d %H:%M'
echo
echo 'stn  ch   date   time   report host:port      time stamp    ch ... status'
echo
#
cat /home/auto/GTA-45U.ch.$host|
while read ch stan
do
  out=`grep " $ch " /dat/log/recvstatus.log|tail -1|sed 's/recvstatus//'`
  echo $stan $ch $out
done
#
