#!/bin/sh
#
# $Id: copy_trg_from_sso,v 1.1.4.1 2010/12/28 12:55:40 uehira Exp $
#

echo cd /dat/trg
cd /dat/trg
while read file
do
  echo rcp sso-jc5:/dat/trg/$file .
  rcp sso-jc5:/dat/trg/$file .
  echo rcp sso-jc5:/dat/trg/$file.ch .
  rcp sso-jc5:/dat/trg/$file.ch .
  echo rm $file.sv
  rm $file.sv
done
