#! /bin/sh
#
# $Id: ee,v 1.3.4.1 2010/12/28 12:55:40 uehira Exp $
#

if [ -z "$WINDIR" ]
then
	WINDIR=/dat
fi
case $0 in
	*ea)	EVTEMP=evtempa;;
	*ee)	EVTEMP=evtemp;;
	*pp)	EVTEMP=pktemp;;
esac
if [ $# -ge 1 -a -d $WINDIR/etc/$1 ]
then
	WINDIR=$WINDIR/etc/$1
	shift
fi
if [ $# -eq 0 ]
then
	more -c $WINDIR/etc/$EVTEMP.`cat $WINDIR/etc/YYMM`
else
	if [ -f $WINDIR/etc/$EVTEMP.$1 ]
	then
		if [ $# -eq 1 ]
		then
			more -c $WINDIR/etc/$EVTEMP.$1
		else
			grep -i '  '$2 $WINDIR/etc/$EVTEMP.$1|MORE= more -d
		fi
	else
		grep -i '  '$1 $WINDIR/etc/$EVTEMP.`cat $WINDIR/etc/YYMM`|
			MORE= more
	fi
fi
