#! /bin/sh
#
# $Id: el,v 1.2 2000/04/30 10:10:38 urabe Exp $
#

if [ -z "$TMP" ]
then
	TMP=.
fi
(cd $1;ls -s) | egrep -v '[A-z]' | cat -n > $TMP/tmp.$$
echo '     #    KB YYMMDD hhmmss'
head -3 $TMP/tmp.$$
echo '     .   ... ...... ......'
tail -7 $TMP/tmp.$$
rm $TMP/tmp.$$
