#! /bin/sh
#
# $Id: el,v 1.2.4.1 2010/12/28 12:55:40 uehira Exp $
#

if [ -z "$TMP" ]
then
	TMP=.
fi
(cd $1;ls -s) | egrep -v '[A-z]' | cat -n > $TMP/tmp.$$
echo '     #    KB YYMMDD hhmmss'
head -3 $TMP/tmp.$$
echo '     .   ... ...... ......'
tail -7 $TMP/tmp.$$
rm $TMP/tmp.$$
