#!/bin/sh
#
# $Id: monitor_procs1,v 1.2.4.1 2008/04/07 05:51:40 uehira Exp $
#
. win.conf
tmp=/tmp/monitor_procs.$$
ps agxww|sed 's/ (.*)$//'> $tmp
cat _win|grep -v '^#'|grep -v '^nice'|sed -n 's/ *&.*$//p'|expand|tr -s " "|
while read procs
do
  pid=`grep "$procs\$" $tmp|awk '{print $1}'`
  if [ -n "$pid" ]
  then
    if [ "$1" = kill ]
    then
      echo kill $pid
#      /bin/kill $pid
      kill $pid
    fi
  else
    echo Not found : \'$procs\'
  fi
done
rm $tmp
