#!/bin/sh
#
# $Id: monitor_procs,v 1.2 2000/04/30 10:10:38 urabe Exp $
#
. win.conf
tmp=/tmp/monitor_procs.$$
ps agxww|sed 's/ (.*)$//'> $tmp
cat _win|grep -v '^#'|grep -v '^nice'|sed -n 's/ *&//p'|expand|tr -s " "|
while read procs
do
  if grep "$procs\$" $tmp >/dev/null
  then
    :
  else
    $procs &
    time=`date +%y%m%d.%H%M%S`
    echo -n $time >> /dat/log/monitor_procs.log
    echo " "$procs >> /dat/log/monitor_procs.log
  fi
done
rm $tmp
