#!/bin/sh
#
# $Id: monitor_procs,v 1.3 2001/05/31 04:05:30 urabe Exp $
#
. win.conf
if [ -z "$TD" ]
then
  TD=/tmp
fi
if [ -z "$DD" ]
then
  DD=/dat
fi
tmp=$TD/monitor_procs.$$
ps agxww|sed 's/ (.*)$//'> $tmp
cat _win|grep -v '^#'|grep -v '^nice'|sed -n 's/ *&//p'|expand|tr -s " "|
while read procs
do
  if grep "$procs\$" $tmp >/dev/null
  then
    :
  else
    $procs &
    time=`date +%y%m%d.%H%M%S`
    echo -n $time >> $DD/log/monitor_procs.log
    echo " "$procs >> $DD/log/monitor_procs.log
  fi
done
rm $tmp
