#! /bin/sh
#
# $Id: newtape,v 1.2.4.1 2010/12/28 12:55:40 uehira Exp $
#
pid=`ps -agx | awk '$5 ~ /(^|\/)wtape$/{print $1}'`
if [ -n "$pid" ]
then
	/bin/kill -HUP $pid
	echo SWITCH EXABYTE signal sent to \#$pid
else
	echo \"wtape\" process not found
fi
