#! /bin/sh
#
# $Id: newtape,v 1.2 2000/04/30 10:10:38 urabe Exp $
#
pid=`ps -agx | awk '$5 ~ /(^|\/)wtape$/{print $1}'`
if [ -n "$pid" ]
then
	/bin/kill -HUP $pid
	echo SWITCH EXABYTE signal sent to \#$pid
else
	echo \"wtape\" process not found
fi
