#! /bin/sh
#
# $Id: printmon,v 1.2.4.1 2010/12/28 12:55:40 uehira Exp $
#
pid=`ps -agxw | cut -c-6,18- | awk '$3 ~ /(^|\/)pmon$/{print $1}'`
if [ -n "$pid" ]
then
	/bin/kill -HUP $pid
	echo PRINT MONITOR signal sent to \#$pid
else
	echo \"pmon\" process not found
fi
