#!/bin/sh
#
# $Id: ras2rpdl2b,v 1.1.4.1 2010/12/28 12:55:40 uehira Exp $
#
sf1=/var/spool/ricoh2/ras2rpdl2.1
sf2=/var/spool/ricoh2/ras2rpdl2.2
if [ -f "$sf1" ]
then
  cat > $sf2
  /home/auto/ras2rpdl $sf1 $sf2 | /usr/ucb/lpr -Pricoh-ps >/dev/null 2>&1
  rm $sf1 $sf2
else
  cat > $sf1
fi
