#!/bin/sh
#
# $Id: ras2lips2b,v 1.1.4.1 2010/12/28 12:55:40 uehira Exp $
#
sf1=/var/spool/canon2/ras2lips2.1
sf2=/var/spool/canon2/ras2lips2.2
if [ -f "$sf1" ]
then
  cat > $sf2
  /home/auto/ras2lips $sf1 $sf2 | /usr/ucb/lpr -Pcanon >/dev/null 2>&1
  rm $sf1 $sf2
else
  cat > $sf1
fi
