#!/bin/sh
#
# $Id: recvstatus_filter,v 1.1.4.1 2010/12/28 12:55:40 uehira Exp $
# recvstatus.log filter
#
awk '{if(substr($7,3)==$4) print $7,$0}' | sort -T /dat/tmp| awk '{print $2,$3,$4,$5,$6,$7,$8,$9,$10}' | uniq -6
