#!/bin/sh
#
# $Id: renlog,v 1.4 2004/08/09 01:42:04 urabe Exp $
# renlog
#   2004.1.29 added 'touch'
#   2004.4.5 added $1 -> log directory
#
if [ -n "$1" ]
then
  if ! cd $1 
  then
    exit
  fi 
else
  cd /dat/log
fi
ls -1 *.log|grep -v recvstatus.log|grep -v wtape.log|
while read file
do
  if [ -f $file.3 ]
    then
    rm $file.3
  fi
  if [ -f $file.2 ]
    then
    mv $file.2 $file.3
  fi
  if [ -f $file.1 ]
    then
    mv $file.1 $file.2
  fi
  if [ -f $file.0 ]
    then
    mv $file.0 $file.1
  fi
  mv $file $file.0
  touch $file
done
