#!/bin/sh
#
# $Id: stlist,v 1.1.4.1 2010/12/28 12:55:40 uehira Exp $
# stanlist
cat /dat/etc/channels.tbl|
awk 'NF >=20 && ! /^#/ {printf("%-12s %-5s  %-8s  %-9s %6d  %s\n",$19,$4,$14,$15,$16,$20)}'|
sort -bu +5 -6 +1 -3
