#! /bin/sh
#
# $Id: windiffq,v 1.1.4.1 2010/11/16 10:55:08 uehira Exp $
#
# Output only whether win files differ.
#

if [ ! -f "$1" -o ! -f "$2" ]; then
    echo "windiffq win1 win2"
    exit 1
fi

# make output temporary files
if [ -z "TMPDIR" ]; then
    TMPDIR=/tmp
fi

tempfoo=`basename $0`
TMPFILE1=`mktemp -t ${tempfoo}` || exit 1
TMPFILE2=`mktemp -t ${tempfoo}` || exit 1

winadd -ns $1 > $TMPFILE1
winadd -ns $2 > $TMPFILE2

diff -rq $TMPFILE1 $TMPFILE2 > /dev/null 2>&1

# md5 $TMPFILE1 $TMPFILE2

RET=$?
#echo $RET

if [ $RET -eq 1 ]; then
    echo "Files $1 and $2 differ"
fi

rm -f $TMPFILE1 $TMPFILE2

exit $RET
